### ISSUE TITLE
Visibility Add-in RLOS produces empty polygon results and has no symbology

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/visibility-addin-dotnet#102]
_From @migueldls on December 13, 2016 18:14_

## Expected Behavior

RLOS Tool should populate output to TOC sybolized by visible/not visible to observer
## Current Behavior

RLOS is adding vis_rlos_conv_polygon to TOC but the feature is empty or corrupt. I appears as if the layer was an output of the vis_rlos_output raster but the polygon layer was created with empty geometry. Also the layer in the TOC is not symbolized correctly  
## Possible Solution

Something wrong with the raster to polygon processes that generated empty geometry 
## Steps to Reproduce (for bugs)

1.Run RLOS
2.Check .gdb for outputs: vis_rlos_output (raster) and vis_rlos_conv_polygons (polygon featureclass)
3.Check vis_rlos_conv_polygons attribute table, verify that attributes are present
4.Add layer to TOC and verify that geometry is not drawing

## Your Environment

* Version used: ArcPro 1.4 (7160)
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile): Windows 7
* Link to your project:

_Copied from original issue: Esri/military-tools-for-arcgis#84_

**Comment by pHill5136** [comment]
@nfeuerstein @topowright RLOS appears to be creating the visibility polygon feature class and adding to toc. It does not display in the map. If you close pro and reopen, the layer displays properly. I am not seeing this behavior in 10.3 so this tells me that this is possibly a regression bug at 10.4 pro.

**Comment by nfeuerstein** [comment]
@dhagens @topowright I believe this issue was fixed at 1.4.  Is that correct?

**Comment by dhagens** [comment]
That is correct.

**Comment by nfeuerstein** [comment]
Fixed at 1.4.  Closing
