### ISSUE TITLE
Visibility- Map Point Tool vs Observer Map Point Tool for RLOS vs LLOS

### ISSUE THREAD

**Issue by Dbarnes1** [Esri/visibility-addin-dotnet#104]
The tooltip over the map point tools in linear line of sight are called observer map point tool and target map point tool respectively, whereas in the radial line of sight tab the observer map point tool is simply called the map point tool. 
## Expected Behavior
tooltip naming convention for both of these should be the same, preferably change the name of the radial line of sight tool to Observer Map Point Tool.

**Comment by pHill5136** [comment]
@nfeuerstein @Dbarnes1 Changed the tooltip for RLOS map point tool from Map Point Tool to Observer Map Point Tool. Pull request https://github.com/Esri/visibility-addin-dotnet/pull/106

**Comment by Dbarnes1** [comment]
@pHill5136 thank you!

**Comment by topowright** [comment]
@Dbarnes1 can we close this issue?

**Comment by Dbarnes1** [comment]
@topowright I just merged #106 so i'll verify in the next build

**Comment by Dbarnes1** [comment]
verified, closing
