### ISSUE TITLE
Visibility Add-in LLOS does not produce layers for Sight Lines or LLOS results

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/visibility-addin-dotnet#105]
_From @topowright on December 8, 2016 23:9_

LLOS tool should populate the TOC and Map with the following four layers: 

Observers
Targets
Sight Lines
LLOS Results

## Expected Behavior
Sight Lines populate to the TOC, bu they do not populate to the map. 
## Current Behavior
![image](https://cloud.githubusercontent.com/assets/5488313/21031401/2abe4cb6-bd9b-11e6-8d6f-e05567031a53.png)

LLOS results are not drawn and sight lines do not show up in the map even though they are in the TOC
## Possible Solution
Issues with GP tools not overwriting layers in a default GDB

## Steps to Reproduce (for bugs)

1.Choose Observers
2.Choose Targets
3.Run the tool LLOS
4.

## Context
Currently LLOS is not being written to the default database; however, the Sight Lines are 
## Your Environment
Windows 8 and Build number 7156 of ArcGIS Pro 1.4

_Copied from original issue: Esri/military-tools-for-arcgis#81_

**Comment by lfunkhouser** [comment]
_From @migueldls on December 9, 2016 0:6_

I'm seeing similar issues using LLOS tool. Not sure if this is Pro limitation.

**Expected Behavior**
Sight Lines are added to TOC symbolized as visible/not visible segments to observer along a sight line. And visible/ not visible target.

**Current Behavior**
Los Output is added to TOC as Single Symbol symbology, user must then have select Unique Values by vis code.

**Environment**
Windows 7 and ArcGIS Pro 1.4 (7156)

**Comment by topowright** [comment]
This has now been fixed.
