### ISSUE TITLE
Poor tooltip name and description for Visibility addin (ArcMap)

### ISSUE THREAD

**Issue by elinz** [Esri/visibility-addin-dotnet#108]
When I hover over the Visibility addin the following tooltip is displayed:
![image](https://cloud.githubusercontent.com/assets/4635490/21274714/62a3689e-c37e-11e6-9541-4499c50005a4.png)

"Show Visibility" - there is no reason to use the verb "Show". Users know that the tool will open or do something.

"Add-in command to show Visibility window." - This doesn't help the user at all. We should be describing what the user can do with the addin. Look at other tools and see how they describe the tool.

**Comment by elinz** [comment]
Tooltip name and description should be:
Visibility

Perform Linear (LLOS) and Radial (RLOS) line of sight analysis. LLOS determines if a target(s) is observable from an observer(s) location. RLOS determines what is visible from observer(s) location based on a given distance and a field of view.

**Comment by dhagens** [comment]
@elinz Ready for testing

**Comment by kgonzago** [comment]
FYI @pHill5136, this issue also affects the single add-in.

**Comment by dhagens** [comment]
@kgonzago, just wanted to make sure we are on the same page.  I made the fix for this in the single add-in.  Did you make the changes for this in the overarching MilitaryToolsForArcGIS addin?

**Comment by topowright** [comment]
I have verified that this has been fixed in the single visibility add-in in ArcMap. It is not fixed in Military Tools add-in.

**Comment by dhagens** [comment]
Kevin is going to make the change in the Military Tools addin.  Not sure if he got to it yet.

Sent from my iPhone

On Jan 6, 2017, at 5:02 PM, Lyle Wright <notifications@github.com<mailto:notifications@github.com>> wrote:


I have verified that this has been fixed in the single visibility add-in in ArcMap. It is not fixed in Military Tools add-in.

-

**Comment by topowright** [comment]
@kgonzago @dhagens I am going to close this issue then.
