### ISSUE TITLE
Poor tooltip name and description for Visibility addin (ArcGIS Pro)

### ISSUE THREAD

**Issue by elinz** [Esri/visibility-addin-dotnet#109]
When I hover over the Visibility addin the following tooltip is displayed:
![image](https://cloud.githubusercontent.com/assets/4635490/21275022/c8adc0c0-c37f-11e6-9405-b81641313abf.png)

"Show Visibility" - there is no reason to use the verb "Show". Users know that the tool will open or do something.

"Show Visibility Dockpane" - This doesn't help the user at all. We should be describing what the user can do with the addin. Look at other tools and see how they describe the tool.

**Comment by elinz** [comment]
Tooltip name and description should be:
Visibility

Perform Linear (LLOS) and Radial (RLOS) line of sight analysis. LLOS determines if a target(s) is observable from an observer(s) location. RLOS determines what is visible from observer(s) location based on a given distance and a field of view.

**Comment by dhagens** [comment]
@elinz Ready for testing

**Comment by topowright** [comment]
I have verified that this has been fixed in the single visibility add-in in ArcGIS Pro 1.4. It is not fixed in Military Tools add-in. @kgonzago FYI.

**Comment by topowright** [comment]
@kgonzago @dhagens I am going to close this issue as well based on the fact @kgonzago  is going to do the updates in Military Tools
