### ISSUE TITLE
Okay button too small

### ISSUE THREAD

**Issue by ACueva** [Esri/visibility-addin-dotnet#112]
The "OK" button looks tiny compared to the other buttons.  Any chance we can make the button bigger?
![12-21-2016 8-41-56 am](https://cloud.githubusercontent.com/assets/3093940/21397678/947dc308-c759-11e6-9843-0478e1da8102.png)

**Comment by topowright** [comment]
This has been verfied in build #1404

![image](https://cloud.githubusercontent.com/assets/5488313/25546353/949b6c00-2c17-11e7-8fde-cf90b195ef22.png)

![image](https://cloud.githubusercontent.com/assets/5488313/25546362/9ff0a4ee-2c17-11e7-9d1a-0462b0e28225.png)
