### ISSUE TITLE
RLOS tool does not add symbology correctly if user deletes features from Project.gdb and re-runs tool.

### ISSUE THREAD

**Issue by migueldls** [Esri/visibility-addin-dotnet#113]
If the user runs the tool correctly the first time and gets good results symbolized by Visible/Non-Visible (Green/Red/Other) and then deletes the results from the TOC and deletes the feature classes from the Project.gdb and re-runs the tool, the outputs are that are added to the TOC are then symbolized generically.
![rlos1](https://cloud.githubusercontent.com/assets/23364449/21399739/b2ddf72a-c761-11e6-8a7f-16367004dac3.png)

![rlos](https://cloud.githubusercontent.com/assets/23364449/21398978/7948675a-c75e-11e6-81c6-243b5da7f179.png)

## Expected Behavior

In a current sesion if a user deletes the feature classes from the project.gdb the tool will continue to symbolize as expected
## Current Behavior

The user deletes the results for the Project.gdb and re-runs the tool, the outputs are that are added to the TOC are not symbolized generically.
## Steps to Reproduce (for bugs)

1.Run RLOS get and get good results symbolized correctly.
2.Delete results from TOC
3.Delete feature classes from project.gdb
4.Re-Run the tool.

## Your Environment

* Version used: ArcPro 1.4 (7190)
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by migueldls** [comment]
@topowright @dhagens Outside of what you guys were seeing this is all I could replicate.

**Comment by topowright** [comment]
@migueldls this has been fixed in the latest build. I have tested this and I do not see the same results. @nfeuerstein, @migueldls is out of the office until Jan 3, may I close this out being that I have verified that it is no longer an issue?

**Comment by nfeuerstein** [comment]
Absolutely.

**Comment by topowright** [comment]
@nfeuerstein thank you
