### ISSUE TITLE
RLOS: Observer Points parameter does not handle coordinates entered in Long Lat order (ArcMap)

### ISSUE THREAD

**Issue by elinz** [Esri/visibility-addin-dotnet#115]
The Coordinate Conversion tool was modified to allow users to enter in coordinates in both Lat Long and Long Lat order. All other tools that allow user to type in coordinates should allow the same.

Tool accepts coordinates to be entered in Lat Long...
![image](https://cloud.githubusercontent.com/assets/4635490/21403202/a70768c8-c770-11e6-8562-bd98d1b19929.png)

Tool does not accept coordinates to be entered in Long Lat...
![image](https://cloud.githubusercontent.com/assets/4635490/21403215/b181f71e-c770-11e6-91bc-edf1ed440a4c.png)

**Comment by kgonzago** [comment]
Addressed in #264 PR

**Comment by topowright** [comment]
I am not able to verify this due to this issue: 
https://github.com/Esri/visibility-addin-dotnet/issues/265

**Comment by kgonzago** [comment]
Will be able to verify now since issue was fixed in this [PR](https://github.com/Esri/coordinate-conversion-addin-dotnet/pull/478).

**Comment by BobBooth** [comment]
This is working correctly in ArcMap 10.3.1 MT 3 and Visibility add-in stand-alone build 119 (6/13/18).
![image.png](https://images.zenhubusercontent.com/5a0f051b8a75884b9087dbee/f8c52086-18b3-4372-b048-a52dbf759d1f)
Updating Visibility June 18 Release doc.

**Comment by dfoll** [comment]
- verified this works
- verified the bullet has been added to what's new about supporting long/lat for input parameters
