### ISSUE TITLE
LLOS: Observer Points/Target Points parameters do not handle coordinates entered in Long Lat order (ArcGIS Pro)

### ISSUE THREAD

**Issue by elinz** [Esri/visibility-addin-dotnet#116]
The Coordinate Conversion tool was modified to allow users to enter in coordinates in both Lat Long and Long Lat order. All other tools that allow user to type in coordinates should allow the same.

Tool accepts coordinates to be entered in Lat Long...
![image](https://cloud.githubusercontent.com/assets/4635490/21403347/40e896ec-c771-11e6-84da-2cb4c880e38f.png)

Tool does not accept coordinates to be entered in Long Lat...
![image](https://cloud.githubusercontent.com/assets/4635490/21403345/3e2ca07e-c771-11e6-846a-9b01c33ddcba.png)

**Comment by kgonzago** [comment]
Picking this up since it is similar to this [issue](https://github.com/Esri/distance-direction-addin-dotnet/issues/217)

**Comment by kgonzago** [comment]
Fixed with #264 PR

**Comment by topowright** [comment]
I am not able to verify this due to this issue: 
https://github.com/Esri/visibility-addin-dotnet/issues/265

**Comment by kgonzago** [comment]
Will be able to verify now since issue was fixed in this [PR](https://github.com/Esri/coordinate-conversion-addin-dotnet/pull/478).

**Comment by kgonzago** [comment]
Changes to CC library affected this Long/Lat issue. Moving this back to `In Progress`

**Comment by kgonzago** [comment]
Needs verification. Re-opening issue.

**Comment by BobBooth** [comment]
This is working in Pro 2.1 and Visibility Add-in (119) - 6/13/18
![image.png](https://images.zenhubusercontent.com/5a0f051b8a75884b9087dbee/cedff423-c412-4a5b-a8de-d7ecc75f636f)
Updating CMS doc for Visibility issues addressed.

**Comment by dfoll** [comment]
verified added to the doc
