### ISSUE TITLE
RLOS: Observer Points parameter does not handle coordinates entered in Long Lat order (ArcGIS Pro)

### ISSUE THREAD

**Issue by elinz** [Esri/visibility-addin-dotnet#117]
The Coordinate Conversion tool was modified to allow users to enter in coordinates in both Lat Long and Long Lat order. All other tools that allow user to type in coordinates should allow the same.

Tool accepts coordinates to be entered in Lat Long...
![image](https://cloud.githubusercontent.com/assets/4635490/21403447/a79d5c10-c771-11e6-9c21-ffe1b3d982af.png)

Tool does not accept coordinates to be entered in Long Lat...
![image](https://cloud.githubusercontent.com/assets/4635490/21403453/adbb8450-c771-11e6-9f7c-ce7fd05d21bb.png)

**Comment by kgonzago** [comment]
Fixed in #264 PR

**Comment by topowright** [comment]
I am not able to verify this due to this issue: 
https://github.com/Esri/visibility-addin-dotnet/issues/265

**Comment by kgonzago** [comment]
Will be able to verify now since issue was fixed in this [PR](https://github.com/Esri/coordinate-conversion-addin-dotnet/pull/478).

**Comment by BobBooth** [comment]
This is fixed in Pro 2.1, Visibility stand alone 119 (6/13/18)
![image](https://user-images.githubusercontent.com/3801392/41379649-81bcfdbc-6f30-11e8-8db8-60892b53d536.png)

Updating CMS what's new for visibility.

**Comment by dfoll** [comment]
verified it is in the doc
