### ISSUE TITLE
LLOS: add progress bar similar to RLOS (ArcGIS Pro)

### ISSUE THREAD

**Issue by elinz** [Esri/visibility-addin-dotnet#120]
When the RLOS tool executes in ArcGIS Pro it displays a progress bar, i.e. the "Input Surface" label changes to a progress bar...
![image](https://cloud.githubusercontent.com/assets/4635490/21433881/8b9572e0-c826-11e6-8d43-7cd6e4572e9b.png)

When the LLOS tool executes it does not display this progress bar.

**Comment by topowright** [comment]
@csmoore what would be the level of effort for this?

**Comment by dfoll** [comment]
This looks like it is working in ArcGIS Pro

**Comment by dfoll** [comment]
moving to done, progress bar is in ArcGIS Pro.
