### ISSUE TITLE
RLOS: Distance parameter does not have a dedicated units control (ArcMap)

### ISSUE THREAD

**Issue by elinz** [Esri/visibility-addin-dotnet#122]
The distance parameter on the RLOS (radial line of sight) tool does not have it's own units control. The distance parameter uses the same units set in the Offsets portion of the interface. This is usability issue as I believe users will want to specify different units for the offset and distance.

![image](https://cloud.githubusercontent.com/assets/4635490/21435911/f738fa1c-c830-11e6-87de-35944a947150.png)

@nfeuerstein Not sure if this is a bug or an enhancement.

**Comment by topowright** [comment]
I do no think this is a bug.

**Comment by topowright** [comment]
@dfoll and @ACueva do you think we need this?

**Comment by topowright** [comment]
@dfoll and @ACueva do you think we need this?

**Comment by topowright** [comment]
Spoke to @dfoll about this and this is something that he feels that we still need this.

**Comment by dfoll** [comment]
verified
