### ISSUE TITLE
RLOS: Distance parameter does not have a dedicated units control (ArcGIS Pro)

### ISSUE THREAD

**Issue by elinz** [Esri/visibility-addin-dotnet#123]
The distance parameter on the RLOS (radial line of sight) tool does not have it's own units control. The distance parameter uses the same units set in the Offsets portion of the interface. This is usability issue as I believe users will want to specify different units for the offset and distance.

![image](https://cloud.githubusercontent.com/assets/4635490/21435987/41b6e522-c831-11e6-9240-e374a8f790f4.png)

@nfeuerstein Not sure if this is a bug or an enhancement.

**Comment by nfeuerstein** [comment]
@elinz even there was only one unit configuration that applied to all inputs, it is odd to have it placed in the Offsets section only when it applies to distance as well.  That said, the user can get around with the clunkiness until next release.

**Comment by elinz** [comment]
@nfeuerstein Sounds good. Thanks.

**Comment by dfoll** [comment]
Verified. This doc has been covered by updating the workflows from issue #279
