### ISSUE TITLE
RLOS: tool is creating data outside analysis area when set to symbolize non-visible data in output (ArcGIS Pro)

### ISSUE THREAD

**Issue by elinz** [Esri/visibility-addin-dotnet#125]
If you check the "Symbolize Non-Visible Data in Output" option, AND set the Field of View so it's not 0 to 360, the output creates non-visible data outside of analysis area.

For example...
![image](https://cloud.githubusercontent.com/assets/4635490/21437148/1e3be6fa-c837-11e6-9959-1ded07a655c2.png)

creates the following output...
![image](https://cloud.githubusercontent.com/assets/4635490/21437155/27d55fc0-c837-11e6-895a-ccd0aad9fc3e.png)

The output should not have any data from 180 to 360. This is very misleading to the user as it implies the analysis was perform for 0 to 360.

**Comment by topowright** [comment]
@dhagens can we take a look at this? The output might be a field of view slice instead of the entire circle.

**Comment by topowright** [comment]
I think this is similar to this issue: 

https://github.com/Esri/visibility-addin-dotnet/issues/124

**Comment by dhagens** [comment]
@nfeuerstein @topowright @mfunk @lfunkhouser @kgonzago 

@elinz After doing some more research on this, this isn't something that we can make work in a timely fashion.  I would expect this to take several days to a week to make work properly.  We do not have a GP tool that will allow us to create a feature based on headings from a given point, that would then be used to clip the buffer polygon used within the Visibility tool.  We would either have to create our own GP tool (such as the fan tool) or compose a solution in ArcObjects.  If you run the Visibility GP tool in ArcMap, you'll notice that the output displays NoData values for the entire input surface.  We've gone one step further in our tool to only display the NoData values within the Max Distance from the Observer Point.
The following is the output in ArcMap running the Visibility tool with one Observer point, max distance of 1000m and Horizontal start/end angles of 180 -> 360
![image](https://cloud.githubusercontent.com/assets/13664546/21648123/de9ab088-d26a-11e6-8f10-d4df0fc5030b.png)

When zoomed into the Observer Point, you'll notice that the Visibility tool was run with Horizontal start/end angles of 180 -> 360, yet the output displays NoData values for everywhere.
![image](https://cloud.githubusercontent.com/assets/13664546/21648206/24b3990e-d26b-11e6-8b8f-b73ef9024f08.png)

This may be a nice feature to add sometime in the future, but given the amount of bugs that we have to fix at this point, and the tight timeframe in which to fix them, my recommendation is to mark this bug as an enhancement (given that it performs as the Visibility GP tool does) and possibly work on it at another time in the future.  Thoughts?

**Comment by csmoore** [comment]
Updated in #179, looks like: 

![image](https://cloud.githubusercontent.com/assets/3090809/24377367/2bff39c4-130d-11e7-956a-47dfb2b3e95d.png)

**Comment by csmoore** [comment]
Ready to verify from daily build.

The intersect step actually adds the clipping polygon so the output looks a little better/cleaner than before:

![image](https://cloud.githubusercontent.com/assets/3090809/24507020/622bcc02-152d-11e7-8d8c-e9d425aee298.png)

**Comment by Dbarnes1** [comment]
verified, closing
