### ISSUE TITLE
LLOS: error message is not clear what action to take (ArcGIS Pro)

### ISSUE THREAD

**Issue by elinz** [Esri/visibility-addin-dotnet#126]
Run the tool with the following parameters...
![image](https://cloud.githubusercontent.com/assets/4635490/21440338/660ff9d4-c847-11e6-8fc1-c5f4758f179d.png)

The tool threw the following message:
LLOS computations did not complete correctly. Please try again by selecting the 'OK' button.

The message dialog and the LLOS tool both have an 'OK' button. The user may think that by clicking the 'OK' button on the message dialog that the tool will re-execute. Let's change the message so that it's clear what they need to do. Also we generally say "complete successfully" not complete correctly...so...

For example:
"LLOS computations did not complete successfully. Please run the LLOS tool again."

**Comment by topowright** [comment]
@elinz This is an issue that was fixed last nights build of ArcGIS Pro. If you update your version of Pro to the daily build and update your add-in this should not be an issue. 

@elinz please verify that you do not see this issue after updating.

**Comment by elinz** [comment]
@topowright The issue was concerning the text that we write to the message box, so it's an issue with the addin and not ArcGIS Pro, so I'm not sure how installing a newer build of ArcGIS Pro would make any difference with our message box. It may make a difference in whether the tool doesn't complete successfully.

**Comment by elinz** [comment]
FYI. There was a fix to the latest build of ArcGIS Pro which should prevent the case where the addin message will need to be displayed. 

I'm closing the issue. If can reopen if there is still an issue.
