### ISSUE TITLE
Graphics temporarily disappear if you use a combination of the Target/Observer Map Point Tool and pasted coordinates

### ISSUE THREAD

**Issue by dfoll** [Esri/visibility-addin-dotnet#130]
If you are using the Target/Observer Map Point Tool to input coordinates and then try to paste in some coordinates the points previously entered with the Target/Observer Map Point Tool disappear. They reappear with a single click of the Target/Observer Map Point Tool, without actually needing to click on the map. 

The same behavior, with the same resolution happens if you have the Visibility pane open, then switch to a different pane such as the Coordinate Conversion pane, then switch back to the Visibility pane.

**Comment by dfoll** [comment]
@nfeuerstein @lfunkhouser  i set the milestone to version next, however this is something i feel may not be critical for the first release, and thus may not need to be milestone next. Feel free to change the milestone, I have actually already explained this behavior in the documentation, so it's your call

**Comment by dhagens** [comment]
If all agree, I think this is a higher priority bug than #94, #124, #125 so I'll look into this one first.

**Comment by dhagens** [comment]
@dfoll, this is ready for testing with new build.

**Comment by dfoll** [comment]
verified
