### ISSUE TITLE
Linear Line of Sight not producing any output

### ISSUE THREAD

**Issue by dfoll** [Esri/visibility-addin-dotnet#131]
Repro:

[insert a new map in pro]
1. remove the topographic basemap from your map
2. add elevation data, in my case i was using "ElevationUTM_Zone10" from the military tools test data gdb, this is available from the github repo.
3. open the visibility pane
4. click on the llos tab
5. use the observer map point tool to select one or many input observers
6. use the target map point tool to select one or many targets
7. leave the defaults
8. click OK
get a warning message "LLOS computations did not complete correctly. Please try again by selecting the 'OK' button."
9. click ok to close the message
10. click ok on the visibility pane again
this time Pro just hangs  just hangs (no windows based program is unresponsive message though)

**Comment by dfoll** [comment]
@mfunk

**Comment by dhagens** [comment]
@dfoll, I cannot reproduce this with the steps provided.  All works fine for me on the current build.
@topowright could you test this on your end and see if you can reproduce it?  I tested with the latest build at \\redarchive2\disl\Development\Commercial\MilitaryToolsForArcGIS\_current\ArcGISPro\Addins

**Comment by topowright** [comment]
I am not able to reproduce this issue either. This could be a relic of a previous add-in. I would blow away all Pro directories in the profile directories and uninstall the add-in and reinstall the single add-in and see if you get the same results.

**Comment by lfunkhouser** [comment]
@dfoll can you verify

**Comment by dfoll** [comment]
this was user error, i did not have 3d analyst licensed
