### ISSUE TITLE
Something Went Wrong error in RLOS- ArcMap 10.5, should be warning about different coordinate systems

### ISSUE THREAD

**Issue by Dbarnes1** [Esri/visibility-addin-dotnet#138]
I added a basemap, then the military tools sample dem to the map and tried to conduct RLOS. I added multiple observer points and clicked OK when...

Something Went Wrong:
![image](https://cloud.githubusercontent.com/assets/13024357/21734787/21066844-d41a-11e6-9877-64f3070dc2d3.png)

What that something is are two different coordinate systems, that of the basemap and that of the elevation layer. This error message should be changed to reflect that. And the progress bar is still moving, which seems wrong.

**Comment by Dbarnes1** [comment]
https://github.com/Esri/visibility-addin-dotnet/issues/61 

So I'm realizing that this issue is due to the fact that the elevation spatial reference didn't match the basemap I was using. However, we need a warning for different data frames. This was apparently fixed last may, but it has been broken since then.

**Comment by topowright** [comment]
I think I have further issues that are similar to this. 

Steps to replicate the dialog: 

![image](https://cloud.githubusercontent.com/assets/5488313/21737312/6fdde80e-d42c-11e6-9a96-afd230abf625.png)


1. Start with a empty data frame
2. Add a non projected layer
3. Add a projected elevation layer

The expected result should be explaining to the user that the data frame is not projected properly.

**Comment by topowright** [comment]
The issue is that there are multiple dialog prompts happening for the same issue. @dhagens

**Comment by lfunkhouser** [comment]
Assigning to @Dbarnes1 to verify

**Comment by Dbarnes1** [comment]
![image](https://cloud.githubusercontent.com/assets/13024357/21788161/e5b3b804-d681-11e6-8154-9edac086ab69.png)


verified. Thanks @dhagens
