### ISSUE TITLE
RLOS- output should include symbology for locations where more than 1 observer can see.

### ISSUE THREAD

**Issue by Dbarnes1** [Esri/visibility-addin-dotnet#139]
I thought that RLOS would include a separate color for areas where more than one observer can see. I'm unable to get results for anything other than red (0) and green (1). Wasn't there a purple or yellow for 2, 3, etc.?

It looks like the symbology might just got be getting filled in correctly:
![image](https://cloud.githubusercontent.com/assets/13024357/21736805/32862b96-d428-11e6-8be3-821d3bcae474.png)

There are areas that have a black border in the rlos graphic, but no distinct fill color, only red. My guess is that these are the areas that two observers can see, but the symbology is now being dropped for some reason.

To repro:
conduct a RLOS in Pro 1.4 where two observers are very close together and can likely see much of the same radial area.

**Comment by Dbarnes1** [comment]
@dhagens I'm able to verify that symbology is now being created for two visible observers. Now, there is no fill for any area that is non visible. Is that by design to be consistent with arcmap? If so, I'll go ahead and close this out.

![image](https://cloud.githubusercontent.com/assets/13024357/21865935/f751d254-d7fc-11e6-9ec2-7dce838de53d.png)

![image](https://cloud.githubusercontent.com/assets/13024357/21865950/044971ce-d7fd-11e6-98c5-0851bad76f23.png)

**Comment by dhagens** [comment]
By default, non-visible data is not displayed.  You will need to check the 'Symbolize Non-Visible Data in Output' checkbox if you would like the non-visible data to be symbolized.

**Comment by Dbarnes1** [comment]
@dhagens thanks for the reminder! closing out.
