### ISSUE TITLE
Doc-Visibility: LLOS - coordinate system guidance is incorrect (ArcMap)

### ISSUE THREAD

**Issue by elinz** [Esri/visibility-addin-dotnet#141]
- [x] Step 2 in the "Creating linear lines of sight in ArcMap" section in the military_tools_for_arcgis_desktop.pdf
![image](https://cloud.githubusercontent.com/assets/4635490/21814986/07b1ce6c-d710-11e6-9dab-b8227babbdaf.png)
States "The surface data may be a raster dataset, image service, or mosaic dataset, but it must have the same spatial reference as the data frame." While this is true, it's missing an important requirement that the input surface data be in a projected coordinate system.

The requirements for both the LLOS and RLOS tools in the ArcMap addin are:
1. The input surface is in a projected coordinate system.
2. The data frame is set to the same projected coordinate system as the input surface.

So we should say that the input surface data must be in a projected coordinate system and the data frame must have the same projected coordinate system as the input surface data.

See https://github.com/Esri/visibility-addin-dotnet/issues/118#issuecomment-271620390 for more info.

- [x] The section "Creating linear lines of sight in ArcMap" doesn't need to have ArcMap in the name since the .pdf is for ArcMap.

- [x] The section "Creating radial lines of sight in ArcMap" doesn't need to have ArcMap in the name since the .pdf is for ArcMap.

**Comment by Dbarnes1** [comment]
@elinz this will be ready to verify in the next build of the pdf. I'm going to check on the radial line of sight and the visibility doc in pro to see if anything needs to be changed.

**Comment by elinz** [comment]
@Dbarnes1 Verified that the edits look good in the .pdf included in the 11 Jan 13:51 build of the addin. Closing issue.
