### ISSUE TITLE
Visiblity add in has refresh issue

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/visibility-addin-dotnet#146]
Reproduce:

1 .Add a surface to ArcMap
2. Change the name of the surface in table of contents
3. attempt to collect observer points from the LLOS tab.  Collection will fail.
4. switch to the RLOS tab
5.  The surface will refresh to the new name and now allow points to be collected.

**Comment by dhagens** [comment]
@NatalieCampos this issue has been fixed.  Ready for testing once the code is merged.

**Comment by NatalieCampos** [comment]
this is fine as is.
