### ISSUE TITLE
Symbology not correct for RLOS

### ISSUE THREAD

**Issue by topowright** [Esri/visibility-addin-dotnet#151]
The observer for one observer should be green. After one observer you can move on to other colors. Right now the first observer comes up as red: 

![image](https://cloud.githubusercontent.com/assets/5488313/21939198/800054a0-d973-11e6-9514-a7251adfc4d5.png)

**Comment by topowright** [comment]
@nfeuerstein @lfunkhouser I think that this is a  show stopper. 

@dhagens how hard would this be to do.

**Comment by nfeuerstein** [comment]
@topowright yes, showstopper.  Visible can't be red.

**Comment by dhagens** [comment]
@topowright, @nfeuerstein - I don't agree that this is a showstopper.  These colors are randomly generated.  It just so happened that it was symbolized with red.  It could have been purple or pink just as easily.  If they want to change the symbology color, the user can change it in the Contents Pane

![image](https://cloud.githubusercontent.com/assets/13664546/21947279/647f0516-d9b2-11e6-95c1-5fe2ac4255c1.png)

**Comment by nfeuerstein** [comment]
@dhagens @topowright did we use to apply symbology to the output?  I had thought that visible was always green and non visible was always red.

**Comment by dhagens** [comment]
@nfeuerstein - Green and red are used for LLOS.  We use arbitrary colors in RLOS to designate how many observers can see a location.

![image](https://cloud.githubusercontent.com/assets/13664546/21947393/05602668-d9b3-11e6-8712-bd8649cf173c.png)

**Comment by dhagens** [comment]
![image](https://cloud.githubusercontent.com/assets/13664546/21947413/1680621e-d9b3-11e6-98ee-f7f860863865.png)

**Comment by nfeuerstein** [comment]
Got it.

**Comment by topowright** [comment]
verified
