### ISSUE TITLE
The delete option of the right click dialog doesnt delete the selected coordinate

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/visibility-addin-dotnet#153]
Issue: The delete option of the right click dialog doesn't delete the selected coordinate from Observer or Target points.

To reproduce:

1.  Add Observer Points or Target points.   
2.  Right click and select delete to delete one of the observer points or the target points.
3. See that the observer/target  point was not deleted.

The delete all option does work, however.

**Comment by csmoore** [comment]
If you first **left** click the point(s) to highlight/select it in the list box - the delete does work.

We just want to make the **right** click also select this list box item before bringing up the delete context menu.

**Comment by csmoore** [comment]
@NatalieCampos - this is ready to test in next daily.

The behavior implemented was:

1. If nothing is selected before the right click, delete will select and delete the current item
2. If items are already selected before the right click, delete will delete those (this is so the multiselect/delete will still work)

**Comment by NatalieCampos** [comment]
Verified
