### ISSUE TITLE
Offsets - Change label to Height (above surface)

### ISSUE THREAD

**Issue by joebayles** [Esri/visibility-addin-dotnet#156]
In both the LLOS and RLOS tabs, we refer to height as an offset.

![image](https://cloud.githubusercontent.com/assets/5016557/22048962/497201ca-dce5-11e6-8955-3345467fc3d0.png)
![image](https://cloud.githubusercontent.com/assets/5016557/22048976/5a7a5418-dce5-11e6-887a-65e11d292aee.png)

I know there was some discussion about why we use the _offset_ instead of the _height_, but the fact remains that we are discussing observer or target height, and not offset. [Offset](http://pro.arcgis.com/en/pro-app/help/editing/offset-polyline-.htm), in my opinion, could be confused for horizontal instead of vertical adjustment.

While this may be correct in a [Viewshed analysis](https://pro.arcgis.com/en/pro-app/tool-reference/spatial-analyst/using-viewshed-and-observer-points-for-visibility.htm#ESRI_SECTION1_E858A064D6AB4B7F9E95316D72627ED9) sense, I am assuming that our customers don't think in terms of z-value offset from the elevation service as much as they think in terms of height above or below the ground.

I suggest we simply say height.

FYI @topowright @dfoll

**Comment by csmoore** [comment]
Just verifying that there is agreement to change this label to "Height" (or "Height Above Surface")

**Comment by joebayles** [comment]
Besides holistic testing feedback, when demoing this to the Defense User Group, a group of twenty users did not understand that "Offset" meant "Height".

**Comment by nfeuerstein** [comment]
I agree with @joebayles, given the target audience for these tools, "height" would be better than "offset"

**Comment by csmoore** [comment]
Changed addins' label in #195 -

![image](https://cloud.githubusercontent.com/assets/3090809/26318442/14ea4140-3ee9-11e7-9a67-807677be3d9b.png)

Noticed this was called "Height Above Surface" in the Military Tools GP Tools so just used this for consistency:

![image](https://cloud.githubusercontent.com/assets/3090809/26318327/caea40c2-3ee8-11e7-9905-01194088b95f.png)

**Comment by NatalieCampos** [comment]
verified and closed
