### ISSUE TITLE
Remove Clear Graphics button from RLOS tab

### ISSUE THREAD

**Issue by joebayles** [Esri/visibility-addin-dotnet#157]
![image](https://cloud.githubusercontent.com/assets/5016557/22050445/c30498ae-dcef-11e6-9e75-fa3b098bd63d.png)
![image](https://cloud.githubusercontent.com/assets/5016557/22050549/b4570e1c-dcf0-11e6-99f4-1c55b8f5470a.png)

This button cannot be used in the RLOS workflow (it is never enabled), and should be removed.

Update: related to #154

**Comment by topowright** [comment]
I have verified this issue is completed; however, it looks like it was still in verify, but had already been done by @NatalieCampos. Not sure why it still shows open. Closing it now.
