### ISSUE TITLE
Map Point tool issues (ArcGIS Pro)

### ISSUE THREAD

**Issue by elinz** [Esri/visibility-addin-dotnet#158]
Tested build 17 Jan 2017 13:13.

The Map Point tools on the LLOS and RLOS can't be disabled.

### Current Behavior: 
The Observer and Target Map Point tool can't be disabled on the following tools: LLOS and RLOS. All these tools have the following behavior:
- Click on Map Point tool to enable. Result: The tool is made active and provides coordinates from map as you move cursor over map. Cursor is crosshairs with center dot. There is not change to the look of the button to indicate that it's active...
![image](https://cloud.githubusercontent.com/assets/4635490/22050218/be9f6a8e-dced-11e6-9eb9-bca11eebe8be.png)
- Click on Map Point tool to disable. Result: The tool is not disabled (i.e. still provides coordinates from map as you move cursor over map).

### Expected Behavior (at least what I would expect)
- When tool tab is clicked, the Map Point tool should be disabled by default.
- User clicks the tool to enable.  Result: the tool is enabled; the look of the button changes to indicate that's it's active; the cursor icon changes to the crosshairs with center dot. (other behavior is the same...i.e. interact with map, etc).
- User clicks the tool to disable. Result: the tool is disabled; the look of the button changes to indicate that's it's active; the cursor icon changes back to whatever was the active cursor in ArcGIS Pro before the Map Point tool was made active.

**Comment by csmoore** [comment]
@elinz - this should be ready to verify from daily

**Comment by topowright** [comment]
I have verified this fix.
