### ISSUE TITLE
Specify unit of measure for RLOS distance

### ISSUE THREAD

**Issue by joebayles** [Esri/visibility-addin-dotnet#160]
We should either:
- allow the user to specify a unit of measure for linear distance different than the offset units
- move the unit offset/distance unit of measure drop-down outside of either box

I suggest the former.
![image](https://cloud.githubusercontent.com/assets/5016557/22051339/38d7f70e-dcf7-11e6-9a94-ee8219580ca6.png)
![image](https://cloud.githubusercontent.com/assets/5016557/22051346/416fd2b0-dcf7-11e6-8268-9f274bd50a3f.png)

**Comment by topowright** [comment]
Thinking about this issue further we are asking the users to have the inputted data in a PCS, which means they would be dealing with meters most of the time. I am not sure if this makes sense. to do. @ACueva or @dfoll what are your thoughts on this issue?

**Comment by topowright** [comment]
This is a duplicate issue: 
https://github.com/Esri/visibility-addin-dotnet/issues/122
