### ISSUE TITLE
LLOS- 3D Target output labels are difficult to read in ArcGIS Pro

### ISSUE THREAD

**Issue by Dbarnes1** [Esri/visibility-addin-dotnet#162]
When you run visibility in a scene in pro, everything runs as expected, the only issue I have is that I can't see target visibility labels against dark backgrounds because the label no longer falls within the green background of the target point:

![image](https://cloud.githubusercontent.com/assets/13024357/22161449/3a87c854-deff-11e6-913c-3d19ea230513.png)

For reference, here is how much cleaner it looks in 2D map: 
![image](https://cloud.githubusercontent.com/assets/13024357/22161473/4e8616c6-deff-11e6-95de-1477a54e742e.png)

There are many manual workarounds, including resizing the target points, the labels themselves, or changing the color scheme of your input elevation from a white/black gradient to a green/yellow/beige gradient (or something more unique). However, I think we should try and make our default output in 3D look just as good as the 2D one.

**Comment by topowright** [comment]
This has been addressed and verified. The symbology has been improved.
