### ISSUE TITLE
RLOS output clipped when run in 3D Map in ArcGIS Pro

### ISSUE THREAD

**Issue by BobBooth** [Esri/visibility-addin-dotnet#169]
I ran a RLOS (Military Tools 1.0 in ArcGIS Pro 1.4.1) on sample data in 2D view using a radius of 10000 and Observer height of 300. The output looks good. I wanted to check it in 3D, so I used View> Convert 2D to 3D. The output still looked good. 
I ran the tool in 3D, and the results looked mostly correct, but the edge of the RLOS circle was cut off before the edge of the surface data. Ran again and saw the same issue but cutting off the other side of the circle. See below (my red lines added for emphasis).
![image](https://cloud.githubusercontent.com/assets/3801392/23185127/44a8ccba-f850-11e6-8580-ebcdf0aa3a65.png)
This does not correspond to the edge of the terrain data.
![image](https://cloud.githubusercontent.com/assets/3801392/23185160/64f766de-f850-11e6-8bd2-fc5e914fe59e.png)
Map_3D coordinate system GCS WGS 1984.
Map (original) coordinate system WGS 1984 Web Mercator Auxiliary Sphere
Surface data coordinate system WGS 1984 UTM Zone 10N

**Comment by BobBooth** [comment]
This also happens with the Visibility component add-in.
![image](https://cloud.githubusercontent.com/assets/3801392/23186203/4c12065c-f854-11e6-8c71-d928baacb5da.png)
LLOS seems to be working fine in the same area.

**Comment by topowright** [comment]
This is still an issue with the Add-in. 

![image](https://cloud.githubusercontent.com/assets/5488313/25767967/1b13769c-31b3-11e7-82c8-e4c9969b3e0e.png)


From reading the info above this is an issue with the GP tool and the Add-in. I wonder if this is a issue that we cannot control and is a core issue.

**Comment by topowright** [comment]
The tool runs correctly in 2D , but it does not run correctly in 3D.

**Comment by topowright** [comment]
I am also getting this output at times in 2D. I think this is a high priority issue. @nfeuerstein

**Comment by topowright** [comment]
I see that this is fixed at build #1427
