### ISSUE TITLE
Typo Visibility add in (component) readme file

### ISSUE THREAD

**Issue by BobBooth** [Esri/visibility-addin-dotnet#170]
The readme file for the release for ArcGIS Pro 1.4 contains a typo in the date.
Release Feburary 10, 2017:

Should be:
Release February 10, 2017:

**Comment by csmoore** [comment]
Assigning to PEs to update this on the Download Items & Download site

**Comment by NatalieCampos** [comment]
@dfoll we should make sure to correct this when we release next

**Comment by dfoll** [comment]
yes, i saw that and thought the same thing... unless management wants us to fix everything that is already out there, this is really something that just gets fixed at the very end

**Comment by lfunkhouser** [comment]
Fixed on \\<server archive>\disl\Development\Commercial\ReleaseStaging\June2017Release\Components\Visibility
