### ISSUE TITLE
Select [an] existing feature(s) as inputs

### ISSUE THREAD

**Issue by joebayles** [Esri/visibility-addin-dotnet#172]
As a user, I want to the ability to choose existing features as inputs for LLOS Observers and Targets and RLOS Observers.

- [x] Update applicable workflow topics
   - [x] Create linear line of sight - @dfoll
   - [x] Create radial line of sight - @dfoll
- [ ] ~Update the home page for the August 2018 release~
- [x] Update the Defense what's new - @dfoll
- [x] Create a August 2018 release CMS topic - @BobBooth 
- [x] Update the August 2018 CMS topic - @dfoll
- [x] Update the August 2018 CMS topic (Military Tools) - @dfoll
- [x] Update checklist test
- [x] Do the checklist testing

**Comment by topowright** [comment]
This will involve a UI change for both tabs. I would think that we would use the same approach that is used when using a feature set.

**Comment by csmoore** [comment]
This will impact much of the UI and workflow. For this case/release it might be best to point the users to the GP tools that do this already: https://github.com/Esri/military-tools-geoprocessing-toolbox

**Comment by dfoll** [comment]
This is working as I would expect with one exception. The tool does not honor individually selected features from the feature class I use as input.... example ... the tool always tries to run on all features in the feature class used as input and ignores that you have features from that feature class selected. I do not know if this was part of the original design for this functionality or not.

[Test_data_Vis.zip](https://github.com/Esri/visibility-addin-dotnet/files/2236578/Test_data_Vis.zip)

**Comment by dfoll** [comment]
- do not need to update the home page for Vis or MT because we are only listing new software versions that we support and then directing users to go to the resources page
- doc work is done and ready for review. cms work is already showing on DEV. What's new page will require a build to DEV

**Comment by topowright** [comment]
There was talk of making this issue cover not only selecting a feature class, but selecting features within a feature class. @CTLocalGovTeam if this can be done in this issue lets keep this issue going allowing a user to point to a feature class with multiple features in the data set, but always overriding the selection for the entire file. This is the exact workflow that our gp tools conduct as well.

**Comment by dfoll** [comment]
@topowright  and myself will verify this issue as a minimum deliverable for the MT3.1/Vis Aug release. Functionality to run visibility on a selection set from a feature class with be opened up in a new issue.

**Comment by topowright** [comment]
This issue will be moved to for review and the selecting features from a feature class.
