### ISSUE TITLE
RLOS in 3D in Pro- Input points have too much vertical exaggeration

### ISSUE THREAD

**Issue by Dbarnes1** [Esri/visibility-addin-dotnet#173]
When running RLOS in a scene, the tool will run, and the input points show up in the contents pane as 3D layers. This default is ok, except that there appears to be too much vertical exaggeration of the points. I don't see any vertical exaggeration, cartographic offset, or any other default appearence settings enabled when the tool runs, which is why this is confusing. For now, you can just turn it into a 2D layer, but the 3D layer should accurately reflect the offset you enter in the parameters of the add-in.

**Comment by topowright** [comment]
With the updates to Military Tools in the way that we draw the points in 3D this is no longer an issue: 
![image](https://user-images.githubusercontent.com/5488313/44865606-a539af80-ac37-11e8-862f-df2a6ba7fa66.png)
