### ISSUE TITLE
Documentation - improve instructions for adding the stand-alone add-in to ArcMap

### ISSUE THREAD

**Issue by Dbarnes1** [Esri/visibility-addin-dotnet#180]
Currently, there is a gap in instructions between adding the add-in to ArcMap and instructions explaining functionality. We need to add these instructions to the documentation for visibility, as the add-in doesn't automatically get added to the toolbar.

These are the instructions for Coordinate Conversion. They are identical for what we need for Visibility:

_Click Customize Mode under Customize menu
Customize window appears._

_Select the Commands tab
Select Add-In Controls from Categories
Drag and drop Coordinate Conversion tool from Commands onto an existing toolbar
Close the Customize window_

**Comment by dfoll** [comment]
please verify on solutions pages (dev)  and .pdf
pdf locations are in onenote

**Comment by NatalieCampos** [comment]
@dfoll did you add these doc changes?  I dont see them on SolutionsDev pages.  I also checked xmetal and couldnt find them.  I am going to leave this alone til we get to discuss it.

**Comment by NatalieCampos** [comment]
@dfoll 
I figured it out.  Verified and closing.
