### ISSUE TITLE
BUG-000103064  When using an ArcMap Standard Single Use license, the Radial Line of Sight (RLOS) tool in the Military Tools for ArcGIS in ArcMap add-in returns the following error, "Verify that the Spatial Analyst extension is available and authorized for use."

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/visibility-addin-dotnet#186]
_From @lfunkhouser on April 27, 2017 20:2_

<div><div>STEPS TO REPRODUCE:<br><br>1. If needed, download and install the Military Tools addin for ArcMap from here: http://solutions.arcgis.com/defense/help/military-tools/<br>2. In your ArcGIS Administrator, set your license type to Standard Single Use<br>3. Download and unpack the attached map package (see case attachments). This has a raster you can use to test (we have reproduced the issue with multiple raster datasets)<br>4. Double check that you have spatial analyst authorized and turned on in ArcMap<br>5. Run the RLOS tool and notice you get an error message to ensure your Spatial Analyst is authorized. Make sure you are using the RLOS tab and not the LLOS tab (it will not get an error).<br>6. Try running another tool that requires spatial analyst, such as the raster calculator, and notice that it works<br>7. Close ArcMap and change your license type to Standard Concurrent Use<br>8. Start ArcMap and do try to run RLOS again - you will no longer get an error message. You will also not get an error message with Advanced Single Use.</div><div>
<span><b>Salesforce ID:</b> BUG-000103064</span><br/>
<span><b>Salesforce Submitter:</b> AJ Johnson</span><br/>
<span><b>Salesforce Submit Date:</b> 2/21/2017 12:36 PM</span><br/>
<span><b>Salesforce Bug Type:</b> Failure/Error</span><br/>
<span><b>Salesforce Severity:</b> Medium</span><br/>
<span><b>Repro Data:</b> (n/a)</span><br/>
<span><b>Work Around:</b> Install an ArcMap Advanced Single Use license.</span><br/>
<span><b>Product:</b> ArcGIS for Defense</span><br/>
<span><b>Functional Category:</b> ArcGIS for Defense</span><br/>
<span><b>Client Platform:</b> (n/a)</span><br/>
<span><b>Version Found:</b> 10.4.1</span><br/>
<span><b>Planned Version Fixed:</b> (n/a)</span><br/>
<span><b>Comment:</b> Will be fixed in next release</span><br/>
</div></div>

_Copied from original issue: ArcGIS/solutions-desktop-templates#348_

**Comment by topowright** [comment]
Looking closer at this issue when a user tries and run the add-in without having spatial analyst turned on it throws the following error: 
![image](https://cloud.githubusercontent.com/assets/5488313/25569186/d3d4fca0-2dc6-11e7-860e-415da9699074.png)
The prompt should tell the user to turn on the spatial analyst extension. 

After turning on the extension the tool the runs correctly.

**Comment by topowright** [comment]
@kgonzago @mfunk @Dbarnes1  is this the same experince you had?

**Comment by mfunk** [comment]
Not quite the same. Ours was definitely license related, not just having Extension not turned on.

**Comment by csmoore** [comment]
@topowright not sure which version you are testing with (final, patch, or latest dev), using the latest dev branch on 10.4, if I try to run RLOS with the extensions turned off I get:

![image](https://cloud.githubusercontent.com/assets/3090809/25581858/32b24c46-2e58-11e7-8ea1-20ad0e246120.png)

**Comment by csmoore** [comment]
Testing some more I did see some bad behavior in some circumstances (including @topowright 's [comment/screenshot](https://github.com/Esri/visibility-addin-dotnet/issues/186#issuecomment-298265954) ) so tried to address in latest PR #187.

**Comment by topowright** [comment]
I will conduct some further testing in 10.3.1, 10.4.1 , and 10.4.1.

**Comment by lfunkhouser** [comment]
Assigning to @topowright and adding ```verify``` label for @csmoore's updates

**Comment by topowright** [comment]
@csmoore @kgonzago I have verfied that this issue is now fixed in build #1413
![image](https://cloud.githubusercontent.com/assets/5488313/25597478/b6e0e31c-2e83-11e7-925e-fa702696eed8.png)
