### ISSUE TITLE
map point tool does not activate on map

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/visibility-addin-dotnet#190]
This is seen in build both the full addin (build 1487) and the individual component(9:06am).  To reproduce:
1. Add an elevation layer to map. Either a local dataset or an image service 
2. On either the LLOS or the RLOS tab (both are broken)
3. Click the map pointer tool
4. Attempt to click on map

The map pointer tool never activates the cross hairs.  This prevents any points on the map from being collected.  This is seen in ArcMap10.3.1.and 10.5.

**Comment by NatalieCampos** [comment]
@csmoore this is only seen in ArcMap.

**Comment by csmoore** [comment]
I could reproduce this - it  this was broken in #159 / #176 and was a bug with attempting to save the last tool when it was null (no tool current active tool - which happens whenever you enter "customize" mode) - addressed in #192

**Comment by NatalieCampos** [comment]
verified.
