### ISSUE TITLE
BUG-000105205  Error Results not calculated. Check input parameters and try again when using image service with RLOS command in Military Tools Toolbar

### ISSUE THREAD

**Issue by nfeuerstein** [Esri/visibility-addin-dotnet#191]
<div><div>
<span><b>Salesforce ID:</b> BUG-000105205</span><br/>
<span><b>Salesforce Submitter:</b> Andrew Johnson</span><br/>
<span><b>Salesforce Submit Date:</b> 5/17/2017 7:56 AM</span><br/>
<span><b>Salesforce Bug Type:</b> Failure/Error</span><br/>
<span><b>Salesforce Severity:</b> Medium</span><br/>
<span><b>Repro Data:</b> (n/a)</span><br/>
<span><b>Work Around:</b> (n/a)</span><br/>
<span><b>Product:</b> ArcGIS for Desktop</span><br/>
<span><b>Functional Category:</b> ArcGIS for Defense</span><br/>
<span><b>Client Platform:</b> (n/a)</span><br/>
<span><b>Version Found:</b> 10.5</span><br/>
<span><b>Planned Version Fixed:</b> (n/a)</span><br/>
<span><b>Comment:</b> (n/a)</span><br/>
</div></div>

**Comment by csmoore** [comment]
This should be resolved with #184

**Comment by NatalieCampos** [comment]
This issue was resolved in #184
