### ISSUE TITLE
ENH-000105194  Adjust the Visibility tool from the Military Tools for ArcGIS solution in ArcGIS Pro dark theme so the text can be read more easily

### ISSUE THREAD

**Issue by nfeuerstein** [Esri/visibility-addin-dotnet#198]
<div><div>
<span><b>Salesforce ID:</b> ENH-000105194</span><br/>
<span><b>Salesforce Submitter:</b> Sarah Bubka</span><br/>
<span><b>Salesforce Submit Date:</b> 5/16/2017 1:20 AM</span><br/>
<span><b>Salesforce Bug Type:</b> Product</span><br/>
<span><b>Salesforce Severity:</b> Low</span><br/>
<span><b>Repro Data:</b> \\esri.com\sf_filestore\PRD\Attachments\Defects\ENH-000105194</span><br/>
<span><b>Work Around:</b> 1. Provide the appropriate/comparable step by step workflow to help illustrate the request.<br>&gt;Download the solution from http://solutions.arcgis.com/defense/help/military-tools/<br>&gt;Assign dark theme in ArcGIS Pro<br>&gt;Install the Add-In. On the Military Tools tab, open the Visibility tool<br>&gt;On the RLOS tab, there is a lot of black text on the dark grey background so it is tough to read<br><br>2. What is the problem feature X is trying to solve? (i.e. What is the problem/limitation/design choice that is preventing the customer from moving forward?)<br>The dark text on a dark background is tough on the eyes and it would be easier to use if the text were white. <br><br>3. What are the benefits or changes that would result from the enhancement? (i.e. How does making this change help the customer&#39;s workflow or business?)<br>It will be a much better user experience if all of the text on the tool is easy to read.<br> </span><br/>
<span><b>Product:</b> ArcGIS Pro</span><br/>
<span><b>Functional Category:</b> ArcGIS for Defense</span><br/>
<span><b>Client Platform:</b> (n/a)</span><br/>
<span><b>Version Found:</b> 1.4.1</span><br/>
<span><b>Planned Version Fixed:</b> (n/a)</span><br/>
<span><b>Comment:</b> (n/a)</span><br/>
</div></div>

**Comment by csmoore** [comment]
Below is the screenshot from this issue (Note: this issue is also being tracked at: https://github.com/Esri/military-tools-desktop-addins/issues/2 )

But in addition to these, I wasn't able to see added points at all in the observer/target list boxes, not sure if this is a new problem, but will try to fix this also.

![image](https://cloud.githubusercontent.com/assets/3090809/26452774/2a2b59de-412f-11e7-811a-8ea9ed11ade0.png)

**Comment by NatalieCampos** [comment]
verified  and closed
