### ISSUE TITLE
RLOS - crashes with Mosaic Dataset as input surface

### ISSUE THREAD

**Issue by mfunk** [Esri/visibility-addin-dotnet#20]
RLOS tool is crashing ArcMap when input surface is a Mosaic Dataset. I'm using the _ElevationSurface_ mosaic from the _MilitaryAnalyst-Geoprocessing-Toolbox\testdata_.

[MilitaryAnalyst-Geoprocessing-Toolbox](https://github.com/ArcGIS/MilitaryAnalyst-Geoprocessing-Toolbox)

1) Open Visibility tools
2) Select **RLOS** tab
3) **Input Surface** select _ElevationSurface_
4) Use **Map Point Tool** to select one or two locations on the surface
5) Click **OK**

Crashy-crashy:
![image](https://cloud.githubusercontent.com/assets/3093182/13586032/9100dee6-e473-11e5-9957-78d505e55dc0.png)

**Comment by topowright** [comment]
We did not have a plan to support Mosaic Datasets in the first version.

**Comment by dhagens** [comment]
I believe this was fixed with a previous fix that has been merged.  I tested this in 10.5 and both LLOS and RLOS seem to work fine now when a mosaic dataset is used as the input surface.

**Comment by csmoore** [comment]
Verified

![image](https://cloud.githubusercontent.com/assets/3090809/23414619/99bf3856-fdaa-11e6-91b2-64264fb01108.png)
