### ISSUE TITLE
RLOS output results not matching input parameters - ArcMap

### ISSUE THREAD

**Issue by dfoll** [Esri/visibility-addin-dotnet#206]
The distance I input for the RLOS is not reflected in the circle polygon that is generated.  See the attached image.  Note I put in a distance of 1000.  I assume based on documentation that it is in Feet, the unit selected in the drop down box.  But when I use the Line measuring tool the distance is calculated to be 92.8 feet.  ??? 
 
When I input 10000 the linear distance is 928 feet.
 
When I switch to meters and input 500, the distance is measured to 46.5 meters.
 
Is there a conversion error going on here?  Could it be something with my selected coordinate system?
 
This is what projected coordinate system I am using in my test case:
 
NAD_1983_StatePlane_Washington_North_FIPS_4601_Feet
WKID: 2285 Authority: EPSG
 
Projection: Lambert_Conformal_Conic
False_Easting: 1640416.666666667
False_Northing: 0.0
Central_Meridian: -120.8333333333333
Standard_Parallel_1: 47.5
Standard_Parallel_2: 48.73333333333333
Latitude_Of_Origin: 47.0
Linear Unit: Foot_US (0.3048006096012192)

**Comment by dfoll** [comment]
came to us internally through Karl from Mark Wade. He was experiencing this in ArcMap, once I have a 2.0 compatible version of the add-in, i'll check on it in Pro as well

**Comment by dfoll** [comment]
@nfeuerstein verified, this is reproducible, writing up steps now it to be fixed

**Comment by dfoll** [comment]
Repro steps:
1. Add the ElevationUTM_Zone10 to your map
2. Set the data frame coordinate system to WGS_1984_UTM_Zone_10N (you can just import the coordinate system from that data source)
3. Select an observer point
4. Expand observer options
5. use whatever you like for observer and surface height above surface
6. set units to feet
7. set distances of 0 to 1000 
8. click OK to run
9. use the measure tool to check the distance from the observer to the outer edge of the rlos area
10. it should check out, at 1000 feet
********
11. remove ElevationUTM_Zone10 from the toc
12. in a browser, navigate to https://wagda.lib.washington.edu/data/geography/wa_state/#elevation
13. click "various links hosted by ESS" (near top of page)
14. Click "data by quad" (near middle of page)
15.  Click the Wenatchee (center of state)
16. Click "Davis Peak" either interactively from the map, or use the table, it is row 1332
17. Unzip locally
********
18.  Use project raster
19. input raster is the "q1332.dem" you just downloaded
20. name the output raster (put it in a geodatabase, if you do not have a test/working .gdb already, make a new one)
21. output coordinate system should be  (easiest way is just to search for the wkid which is "2285")
     NAD_1983_StatePlane_Washington_North_FIPS_4601_Feet
WKID: 2285 Authority: EPSG
 
Projection: Lambert_Conformal_Conic
False_Easting: 1640416.666666667
False_Northing: 0.0
Central_Meridian: -120.8333333333333
Standard_Parallel_1: 47.5
Standard_Parallel_2: 48.73333333333333
Latitude_Of_Origin: 47.0
Linear Unit: Foot_US (0.3048006096012192)

22. Click OK
*********
23. add the new raster data set to your toc
24. set the coordinate system of the data frame to the same as the newly added raster (simplest way is to use the Add > Import option from the dataset you just added to your toc
25. Select an observer point
26. Expand observer options
27. use whatever you like for observer and surface height above surface
28. set units to feet
29. set distances of 0 to 1000 
30. click OK to run
31. use the measure tool to check the distance from the observer to the outer edge of the rlos area
32. it measures to be about 92.8 feet (depending on how accurate you are with the measure tool)






[GitHub206.zip](https://github.com/Esri/visibility-addin-dotnet/files/1086515/GitHub206.zip)

**Comment by dfoll** [comment]
very first write up on this issue is actually just a copy/paste from the customer's email

**Comment by pHill5136** [comment]
please verify

**Comment by ACueva** [comment]
@pHill5136 I don't see a PR associated with this fix.  Do I need to kick off another build to see the changes?

**Comment by pHill5136** [comment]
It was merged in the last hour or so.

**Comment by ACueva** [comment]
Tested.  Measurement seems accurate.  Any inconsistencies can be attributed to the zoom scale and where I clicked on the map.
![2017-06-22_14-42-06](https://user-images.githubusercontent.com/3093940/27457316-20388628-5759-11e7-86fd-fe063621a63d.png)

**Comment by ACueva** [comment]
@karlterrey Sorry, I tested this in Pro.  Testing in ArcMap now.

**Comment by ACueva** [comment]
Assigning back to other PE's to test.  I had tested this in Pro and it appears to be working.
Having machine issues that are not allowing me to test this in ArcMap.

**Comment by NatalieCampos** [comment]
@pHill5136 This is still incorrect in ArcMap.  Following the reproduction steps below, I get a diameter value of 609 ft.  I believe it should be 2000 ft.  See screen grab below. 

![image](https://user-images.githubusercontent.com/5116835/27460230-630c1c86-5767-11e7-839a-8c1e19a2ffe2.png)

**Comment by ACueva** [comment]
@pHill5136 Tested with build 1607. still failing.

**Comment by ACueva** [comment]
Tested, measurement seems accurate now.
Diameter shows 2000 feet. (Expected)

![2017-06-23_10-39-03](https://user-images.githubusercontent.com/3093940/27493856-3a6eb4b6-5800-11e7-97c9-cb887345a46c.png)

**Comment by ACueva** [comment]
@NatalieCampos Mind double checking?

**Comment by ACueva** [comment]
FYI @karlterrey

**Comment by NatalieCampos** [comment]
@ACueva double checked an mine looks good. Closing issue. @karlterrey 

![image](https://user-images.githubusercontent.com/5116835/27494408-9aa6f3f0-5802-11e7-8581-e4a7d55cec95.png)
