### ISSUE TITLE
RLOS - Tooltips not updating when angle unit changed

### ISSUE THREAD

**Issue by adgiles** [Esri/visibility-addin-dotnet#210]
When you change the unit of measure for angles from say degrees to mils the corresponding tooltips do not update as required:

![untitled](https://user-images.githubusercontent.com/3740334/27540892-b23b3c48-5a36-11e7-8930-e2ce12339260.png)

**Comment by csmoore** [comment]
These tooltips (versus the error/validation messages) are typically static - should I just change this to something more generic like: "Valid vertical angular range"

**Comment by dfoll** [comment]
verified fixed with build 1615 in arcmap and pro.

@csmoore the "valid vertical angle" verbage is good for now. in the future an enhancement for the tooltip to understand which unit you have selected in the drop-down would be even cooler if that is possible
