### ISSUE TITLE
RLOS - Using Mils for Horizontal FOV gives incorrect results

### ISSUE THREAD

**Issue by adgiles** [Esri/visibility-addin-dotnet#211]
The results returned when using mils are incorrect (Update: 5 degrees off for ending angle), the following two examples should be 90 degrees for 1600 mils and 180 degrees for 3200 mils:

![1](https://user-images.githubusercontent.com/3740334/27541862-66618198-5a3a-11e7-80bc-1d69f83e9cf5.png)
![2](https://user-images.githubusercontent.com/3740334/27541864-6805d38c-5a3a-11e7-984a-e3d35708e66b.png)

**Comment by csmoore** [comment]
The conversion factor was incorrect for this so this one should be an easy fix:

![image](https://user-images.githubusercontent.com/3090809/27606613-01e57db2-5b4f-11e7-8986-8713d57a94f5.png)

**Comment by dfoll** [comment]
verified fix with build 1615 in pro and arcmap
