### ISSUE TITLE
RLOS - Using Grads for Horizontal FOV gives incorrect results 

### ISSUE THREAD

**Issue by adgiles** [Esri/visibility-addin-dotnet#212]
The results returned when using 399 grads are incorrect (359.1 degrees) (Update: the range fan displayed is off by 5 degrees)

![399](https://user-images.githubusercontent.com/3740334/27543309-bdff5660-5a3e-11e7-9e7e-75b9a723f309.png)

**Comment by csmoore** [comment]
This appears to be the same range fan resolution issue reported in https://github.com/Esri/visibility-addin-dotnet/issues/211#issuecomment-311463577

![image](https://user-images.githubusercontent.com/3090809/27607543-3006aa2e-5b52-11e7-8e5b-735d04e5d7d9.png)

**Comment by dfoll** [comment]
verified fixed in build 1615
