### ISSUE TITLE
RLOS - Validation not updating when angle unit changed 

### ISSUE THREAD

**Issue by adgiles** [Esri/visibility-addin-dotnet#215]
When you change the unit of measure for angles from say degrees to mils the corresponding validation does not update as required, this is similar to issue #210 for Desktop but within Pro the OK button is disabled so the tool cannot be run:

![capture](https://user-images.githubusercontent.com/3740334/27584279-31814672-5aec-11e7-952b-0dd0c2606266.PNG)

![capture](https://user-images.githubusercontent.com/3740334/27584358-8abb6ae2-5aec-11e7-8b20-5a8aefc6fa82.PNG)

![capture](https://user-images.githubusercontent.com/3740334/27584396-b80cbc08-5aec-11e7-9e92-df89c37a77d2.PNG)

**Comment by dfoll** [comment]
verified
