### ISSUE TITLE
RLOS - No style applied to output

### ISSUE THREAD

**Issue by adgiles** [Esri/visibility-addin-dotnet#216]
**Background**
When most users run a RLOS they expect either a return of red areas where I cannot see and green areas where I can see. This can be a bit trickier when having the issues of multiple observers. 

**Current State:** 
We let ArcGIS Pro and ArcMap choose the default symobology for the output
When you run a RLOS no style is applied to the result, instead a default color is applied, not green for visible and red for non-visible

**Expected Enhancement:** 
Add a feature (possibly a drop down menu or radio box) that would control switching between symbolizing all observable areas as green or symbolizing all areas by the number of observers. If there were only one input observer that output would be green and red by default. 
**Sample:** 
![image](https://user-images.githubusercontent.com/5488313/36874804-266cf61c-1d62-11e8-840d-708a27b8c189.png)

**Comment by csmoore** [comment]
Can you provide a screenshot and steps, I do not see this same issue (but the colors in the style applied may not be the desired ones and need changed):

![image](https://user-images.githubusercontent.com/3090809/27606437-42a371e8-5b4e-11e7-8e6b-634ef3f8d046.png)

**Comment by adgiles** [comment]
It's the colors I am referencing, in desktop you get green for visible, red for not visible

**Comment by topowright** [comment]
I believe we should add a radio box that gives the user choice. 

Classic Viewshed (just green and red)
Viewshed by multiple observers (What can be seen by multiple observers; current output)

**Comment by topowright** [comment]
The initial comment in this issue has been updated to reflect the feature requested. @dfoll @ACueva and @lfunkhouser

**Comment by topowright** [comment]
We need to add an option to allow the user to control if they want to see multiple observer areas or just the simple red and green output even though they have multiple observers.
