### ISSUE TITLE
add build number to the ArcGIS Pro add in

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/visibility-addin-dotnet#217]
It would be useful for the add in to have the build number associated with it similar to ArcMap.  This will help ensure we know what build number we are testing or what build we found the issues in.

This is the about ArcGIS Desktop dialog.  It contains the build number 6491.  
![image](https://user-images.githubusercontent.com/5116835/27596508-98b06a26-5b14-11e7-8ef3-d69c44eea936.png)
Adding the build number to the add-ins would make it easier to identify which build we are testing/finding issues in.   I think the build number should go in the red highlighted box below.

![image](https://user-images.githubusercontent.com/5116835/27598267-cc722494-5b19-11e7-9e54-06567d332c6f.png)

**Comment by topowright** [comment]
Here is the code that was used for Coordinate Conversion. 
https://github.com/Esri/coordinate-conversion-addin-dotnet/commit/22fad093d63e196d51497ed57dc1bf8b44097c98

**Comment by topowright** [comment]
We are going to tackle Military Tools for ArcGIS first before this issue. After this it should be very clear on what to do on this issue.

**Comment by topowright** [comment]
Using this issue to build the Jenkins process for creating the final zip and conducting the code changes for the build process: 
- [ ] Documentation for ArcMap
- [ ] Documentation for ArcGIS Pro
- [ ] Move internet shortcut and readme.txt to solutions site
- [ ] Build ArcGIS Pro 2.1
- [ ] Build ArcMap 10.3.1

**Comment by topowright** [comment]
The way forward on this issue is completely understood and possible. My challenge is our logic will not work until MSBuild is put in the path directory . Once that is done we will know if we are able to build the solutions inside of a pipeline script

**Comment by topowright** [comment]
This has been completed and was done with the entire build process in the pipeline script.
