### ISSUE TITLE
Clean up/Delete feature branches

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/visibility-addin-dotnet#221]
Delete the feature branches that were merged into the code and released. If the branch is still active, please update the name of the branch using the feature branch naming convention,  `<first initial><last initial>/<issue#>-<short description>`.

- [x] csm/add-better-gp-error-msgs
- [x] csm/clip-fov-issues-124-125
- [x] csm/dark-mode-list-box
- [x] csm/mils-grads-issues
- [x] csm/patch-extension-patch
- [x] csm/pro-sdk-2.0
- [x] csm/update-to-prodsk2.0
- [x] csmoore/version2.1.1
- [x] issue159-pbh
- [x] issue206
- [x] lw-jenkinsPro2.0-test
- [x] pro-sdk-2.0
- [ ] v2.0
- [ ] v2.1

**Comment by csmoore** [comment]
Done

These are the version/release maintenance branches created as part of the release process so should remain:
v2.0
v2.1

Note: Also v3.0 branch should be created (just noticed this in this repo, but this is probably also true for the other repos)

**Comment by lfunkhouser** [comment]
Verified and closing issue.
