### ISSUE TITLE
LLOS and RLOS slow using image services in Addins

### ISSUE THREAD

**Issue by csmoore** [Esri/visibility-addin-dotnet#231]
LLOS and RLOS are slow using image services. Even with reasonably sized image services (such as county-wide data).

Example run times (depending on service/AOI size):
LLOS takes 1-20mins
RLOS take 20mins-2 hours  

There is a warning that pops-up before you run (when you press OK to execute) 

Repro steps:

1. Add projected image service to ArcMap or Pro (note: not every image service will be projected)
2. Set the map/data frame to the same projection as the image service
3. Run LLOS or RLOS
4. Click OK at the message box warning that this will take a long time 
5. Long wait with no little or no feedback on progress (you do get a spinning wheel but only if you hover over Visibility addin pane) and you are unable to cancel
6. It does eventually run correctly if you wait long enough

Originally noted in #184 but I guess we never opened a new issue specifically for the slowness.

Tested with data from:
Rhode Island:
https://maps.edc.uri.edu/arcgis/rest/services/Atlas_elevation/Mosaic_RITopoBathy/ImageServer 
Maryland county data:
http://lidar.geodata.md.gov/imap/services/Allegany/MD_allegany_dem_m/ImageServer

**Comment by lfunkhouser** [comment]
@csmoore Can you provide some more information. What can be done about this issue? What is the proposed solution? What are the limitations, if any, with core software?

**Comment by BobBooth** [comment]
I think we need to only request the tiles within the bounding box  of the input features. I don't know, but I suspect that a bigger area is being pulled down for the analysis.

**Comment by csmoore** [comment]
It would likely involve first extracting the server data locally (Note: this option must be enabled on the server data for this to work): http://desktop.arcgis.com/en/arcmap/10.3/tools/server-toolbox/extract-data.htm 

This would still be a client-side solution with a several minute lag before processing would start (depending on clip size) - so we might also want to set a smaller maximum range also.

**Comment by BobBooth** [comment]
This is like the case outlined here:
https://github.com/Esri/visibility-addin-dotnet/issues/194
Still think this is important.

**Comment by topowright** [comment]
@lfunkhouser @dfoll @ACueva I feel like we should close this and show all the work in the issue that came in from support #194. 

I think we should calculate based on the extent based on the information put in by the user. The challenge is when a user selects two areas that are not close to each other, but are still small request areas.
