### ISSUE TITLE
Static Code Analyzer : Null Dereference

### ISSUE THREAD

**Issue by jmccausland** [Esri/visibility-addin-dotnet#233]
the SCA report shows there are possible Null Dereference issues in the code.

Most of the flagged code is due to query interfaces via the 'as' keyword.  When it is safe to do a direct cast to an Esri API Interface, we should do that.  Everywhere else, null check and refactor if needed.

The ReSharper tool can assist with this exercise and minimize these issues in the future.

- when safe, change to direct cast
- add null checks and refactor where needed

**Comment by csmoore** [comment]
This task is in progress with about 40% of high-priority SCA issues addressed in branch https://github.com/Esri/visibility-addin-dotnet/tree/csm/%23233-null-dereference

**Comment by csmoore** [comment]
Addressed in PR #277

For simplicity, moving the other SCA Issues to done:  #234 #235 #236 #237 #238 #239 #240 #241 ( https://github.com/Esri/visibility-addin-dotnet/labels/T-SCA )

And these issues can be verified here with this one.

Additional/Important Note: only "Null Dereference" ( #233) and "Unreleased Resource: Streams" (#240) showed up in the Fortify Report for Visibility so the remaining issues were inferred (but were found ex. File Separator ( #238 ), empty catch ( #235) , etc. )
