### ISSUE TITLE
Static Code Analyzer : Error Handling : Overly Broad Catch

### ISSUE THREAD

**Issue by jmccausland** [Esri/visibility-addin-dotnet#234]
- update code to only handle known exceptions
- let the rest bubble up, remove catch(Exception ex)

**Comment by csmoore** [comment]
These didn't show up in SCA report for visibility for some reason but addressed

**Comment by csmoore** [comment]
Moving to done, will be QA/QC'd with #233 - see: https://github.com/Esri/visibility-addin-dotnet/issues/233#issuecomment-371189091
