### ISSUE TITLE
Static Code Analyzer : Streams

### ISSUE THREAD

**Issue by jmccausland** [Esri/visibility-addin-dotnet#240]
- fix with using() statement

```using( var fs = new Stream())```
```{```
```    // do something```
```}```

**Comment by csmoore** [comment]
Done, implementation was slightly different for serializers:

```
TextReader tr = null;

try
{
...
    tr = new StreamReader(filename);
    var temp = x.Deserialize(tr) as VisibilityConfig;
...
}
catch (Exception ex)
{
...
}
finally
{
    if (tr != null)
        tr.Close();
}
```

**Comment by csmoore** [comment]
Moving to done, will be QA/QC'd with #233 - see: https://github.com/Esri/visibility-addin-dotnet/issues/233#issuecomment-371189091
