### ISSUE TITLE
Improve the Documentation for setting up the GP task for the Visibility Widget

### ISSUE THREAD

**Issue by topowright** [Esri/visibility-addin-dotnet#243]
Currently I have received multiple complaints on the documentation is written for standing up the visibility service that empowers the Visibility widget. 

The steps are clear if you have ever published a gp service before; however, there are somethings that we need to either explain or point to core documentation on to allow the user to have an easier time using this widget: 
- [ ] Add information about managed data folder for server
- [ ] Add steps on getting info into the hosted folder

**Comment by topowright** [comment]
@dfoll If we do this doc update in Jan, but do not release until Feb will this doc become available before the release of the tool?

**Comment by topowright** [comment]
We need to figure out how to tackle this problem based on the knowledge that @dfoll has been instructed.

Possible solution could be a link to the documentation on how to conduct a certain step from the prerequisites. This still will not fix the issues of having links in the offline documentation.

**Comment by topowright** [comment]
This information has been moved to WAB and this issue can be closed.

**Comment by topowright** [comment]
I need clarity on what labels we are going to use to allow this issue to be closed.

**Comment by lfunkhouser** [comment]
@topowright It's a "won't fix" here. The user will get this documentation with WAB.
