### ISSUE TITLE
Crash Re-launching ArcMap from mxd with Viz Dock Window open previously 

### ISSUE THREAD

**Issue by csmoore** [Esri/visibility-addin-dotnet#247]
Re-launching ArcMap from mxd with Viz Dock Window open previously causes crash:

Repro Steps:
1. From the Military Tools Toolbar
2. Open Addin Dock Window
3. Close ArcMap
4. Rerun ArcMap by **double-clicking mxd** (see: https://github.com/Esri/military-tools-desktop-addins/issues/33)
5. crash

Related:
https://github.com/Esri/military-tools-desktop-addins/issues/33
https://github.com/Esri/distance-direction-addin-dotnet/issues/471
https://github.com/Esri/coordinate-conversion-addin-dotnet/issues/427

**Comment by csmoore** [comment]
Ready to QA from `Development\Commercial\MilitaryToolsForArcGIS\12-06-2017_1649`

**Comment by dfoll** [comment]
(in progress)
- [ ] removed G-QA Create (Checklist) updated checklist test/no updates needed
**Verified fixed in 10.6** using our build 1649
- [ ] ran through the explicit repro steps
- [ ] ran through the Viz portion of the checklist test (removing G-QA Verify (Checklist) label

**Comment by topowright** [comment]
@dfoll can this be closed?

**Comment by lfunkhouser** [comment]
@dfoll @topowright Is this verified? Verified label was added but no confirmation that it was verified.

**Comment by dfoll** [comment]
i was testing this issue as it (we eventually found out) pertained to [distance and direction](https://github.com/Esri/distance-direction-addin-dotnet/issues/589) and was not experiencing that any of the three add-in windows were causing a crash upon re-opening, but we can put some time into looking into this issue specifically if you want.

**Comment by dfoll** [comment]
10.3.1 With MT build 42
- Open ArcMap, save.
- Open the CC pane, save. 
- Close ArcMap. 
- Reopen ArcMap (no crash)
- Close the CC pane, open the DD pane, save.
- Close ArcMap.
- Reopen ArcMap (no crash)
- Close the DD pane, open the Viz pane, save.
- Close ArcMap
- Reopen ArcMap no crash.
- Close Viz pane, open CC pane, save
- Close ArcMap
-Reopen ArcMap (no crash)
