### ISSUE TITLE
Update the properties and map point button to support dark theme like DD

### ISSUE THREAD

**Issue by topowright** [Esri/visibility-addin-dotnet#253]
Current buttons : 

![image](https://user-images.githubusercontent.com/5488313/34039543-b818d2e8-e144-11e7-9751-4a47fa2f3250.png)

**Comment by topowright** [comment]
This issue is to focus only on the map point tool button and the properties button

**Comment by csmoore** [comment]
Addressed in #254 

Now looks like (Dark vs. Light theme):

![image](https://user-images.githubusercontent.com/3090809/34530238-823d7286-f07c-11e7-965d-b9737c7cb077.png)

![image](https://user-images.githubusercontent.com/3090809/34530253-882995c6-f07c-11e7-9e5b-fe9ae85cf283.png)

**Comment by topowright** [comment]
Pull request was reviewed and merged by @kgonzago. The issue has been fixed and verified.
