### ISSUE TITLE
Update target version for the add-in

### ISSUE THREAD

**Issue by topowright** [Esri/visibility-addin-dotnet#267]
We need to update the target version to be 2.1 based on the version that we are targeting for this release: 
![image](https://user-images.githubusercontent.com/5488313/36297150-f048ca14-12a5-11e8-8b54-768d3335afdc.png)

**Comment by csmoore** [comment]
Addressed in #274

**Comment by topowright** [comment]
Being that you just fixed this I am pulling this into this sprint to verify.

**Comment by topowright** [comment]
![image](https://user-images.githubusercontent.com/5488313/36863928-ef740834-1d3f-11e8-9bae-9060ee5bfd62.png)
