### ISSUE TITLE
Allow observer location to be set via feature actions

### ISSUE THREAD

**Issue by adgiles** [Esri/visibility-addin-dotnet#268]
Enhancement

A Feature action could be added to the widget to allow the input for the observer location to be set from existing features on the map. This will automatically open the widget if closed and set the observer location to the coordinates of the feature used.

![capture](https://user-images.githubusercontent.com/3740334/36421223-98d90568-162f-11e8-8bb8-b712e99762d0.PNG)

https://developers.arcgis.com/web-appbuilder/guide/create-a-feature-action-in-your-widget.htm

**Comment by topowright** [comment]
This issue was moved to ArcGIS/solutions-defense-widgets#48
