### ISSUE TITLE
Text for inputs in the add-in

### ISSUE THREAD

**Issue by dfoll** [Esri/visibility-addin-dotnet#269]

**Comment by dfoll** [comment]
I set up a placeholder to log an issue I was seeing where no text was appearing in the list boxes for LLOS and RLOS pane, but when I started to write the repro steps, I couldn't repro.

**Comment by csmoore** [comment]
@dfoll - we did have a very similar issue 10 days ago (related to CC changes): 

https://github.com/Esri/visibility-addin-dotnet/issues/265 - https://github.com/Esri/visibility-addin-dotnet/issues/265#issuecomment-365616204

So hopefully it was just an issue with having a slightly older build
