### ISSUE TITLE
Unable to paste values into Observer or Target Points text boxes (external sources)

### ISSUE THREAD

**Issue by ACueva** [Esri/visibility-addin-dotnet#273]
Environment tested on:
ArcMap 10.6
Visibility addin- build 109

Steps to reproduce:
1.  Add an Elevation source. (I utilized SRTM data from \\DATASERVER\data\FoundationOverlays\Elevation\MosaicDatasets}
2. Open Visibility addin
3. Attempt to paste: 116.948W 34.73N 
 into either the Observer Points or Target Points field.
  - Note it's not accepting the pasted values
4. Type the following (manually) into the Observer Points text box: 116.948W 34.73N
5. Press Enter.
6. Select 116.948W 34.73N from the Observer Posts text box.
7. Paste this value into the Target Points text box.
- Note, you are now able to paste this value into the text box.

This behavior is also present for the RLOS tab.

**Comment by lfunkhouser** [comment]
@dfoll can you confirm this is no longer an issue in LLOS and RLOS functionality? I believe this is what you used as you demonstrated #116 today.

**Comment by dfoll** [comment]
I can look at it specifically on 10.6, but yes, in general this is one of the things I showed yesterday
