### ISSUE TITLE
Use a spreadsheet (csv) of values as inputs

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/visibility-addin-dotnet#279]
Currently the add-in takes inputs from keyboard and map point tool. This added functionality would allow a user to input values from a spreadsheet or text file.

- [x] updated symbology to display points that are outside the elevation extent @CTLocalGovTeam 
- [x] Update applicable workflow topics
   - [x] Create linear line of sight - @dfoll
   - [x] Create radial line of sight - @dfoll
- [ ] ~Update the home page for the August 2018 release~
- [x] Create a August 2018 release CMS topic - @BobBooth 
- [x] Update the August 2018 CMS topic - @dfoll
- [x] Update the August 2018 CMS topic (Military Tools) - @dfoll
- [x] Update checklist test - @dfoll
- [x] Do the checklist testing

**Comment by CTLocalGovTeam** [comment]
@topowright Please review the screenshots below and confirm whether we need to add import feature as context menu option or as a button

1. Import option in List box context menu 
![import context menu](https://user-images.githubusercontent.com/2959186/41670156-211a0b0c-74d1-11e8-9d20-35b026b3b450.png)

2. Import option as a button
![import button](https://user-images.githubusercontent.com/2959186/41670195-3e3f5f98-74d1-11e8-8998-0eebc665e9f4.png)

**Comment by dfoll** [comment]
- do not need to update the home page for Vis or MT because we are only listing new software versions that we support and then directing users to go to the resources page
- doc work is done and ready for review. cms work is already showing on DEV. What's new page will require a build to DEV

**Comment by dfoll** [comment]
minimum functionality has been delivered for the MT3.1/Vis Aug release. Updating symbology to display points outside of the extent will be delivered for a future release

**Comment by topowright** [comment]
This needs to be closed after final review. This has been delivered in the August 2018 release.
