### ISSUE TITLE
Store LLOS and RLOS results in a organized fashion

### ISSUE THREAD

**Issue by topowright** [Esri/visibility-addin-dotnet#281]
#### Background
Currently we store all analysis results as a featureclass in the root level of the database. We also add all layers in the ToC. 

#### Expected Results
Each Analysis result would be stored in a FeatureData Set marked LLOS_1 or RLOS_1. The 1 represents the number that was ran in that ArcMap or ArcGIS Pro session.
Layers should be added to the Table of Contents (ToC) inside a group layer with a name matching that they live in the database as mentioned above. 
Layers should be added correctly in the group layer for proper symbolization

#### Verfiy tasks
- [x] results are added a feature dataset with the proper name
- [ ] Results are added to the ToC in the correct order inside a group layer
- [ ] Data is symbolized correctly

**Comment by topowright** [comment]
if you take a look at https://github.com/Esri/distance-direction-addin-dotnet this addin creates a featureset and group layer upon first use of the tool. This should help you in understanding how to use this feature for visibility.

**Comment by topowright** [comment]
This is what the Table of Contents would look like in an organized fashsion. All layers from one run of the LLOS or the RLOS would be placed in a Group: 
![image](https://user-images.githubusercontent.com/5488313/41499925-fd2f3f5a-713d-11e8-8345-4eb674e34339.png)

**Comment by dfoll** [comment]
"LLOS_Output_[n]" should draw on top of "LLOS_Sight_Lines_[n]". "LLOS_Output_[n]"

**Comment by dfoll** [comment]
Do not need "All other values" to display for any layer

**Comment by CTLocalGovTeam** [comment]
@dfoll @topowright We have corrected the order of layers and also removed "All other values" as suggested. We will send these updates in a new pull request soon.

**Comment by dfoll** [comment]
I do not think we need doc tasks for this
