### ISSUE TITLE
Visibility dark theme - buttons switch to light version while tools are processing

### ISSUE THREAD

**Issue by BobBooth** [Esri/visibility-addin-dotnet#288]
On the Visibility Add-In panel, using Dark Theme, I'm seeing the Input Point and Tools buttons being rendered using the light version of the the button *while the tool is actually running* (after you click OK).
It doesn't last long,  but it looks a little strange.
The buttons are dark when not in use, and light-blue highlighted when active, but when you add points and then click OK, the buttons seem to flash "on" in white.
![image](https://user-images.githubusercontent.com/3801392/42113676-f3ee120a-7ba0-11e8-86c5-c78c2263d5bd.png)

**Comment by topowright** [comment]
This is still an issue as of today: 
![image](https://user-images.githubusercontent.com/5488313/43535157-10b3c92a-956e-11e8-92be-0e12e95447f5.png)

**Comment by topowright** [comment]
Looking at this issue again today to verify and it is still an issue: @CTLocalGovTeam. If you feel you have a build where you are seeing something different please let me know.
