### ISSUE TITLE
Map Point tool and properties buttons state changes during analysis

### ISSUE THREAD

**Issue by topowright** [Esri/visibility-addin-dotnet#289]
#### Issue
When running  analysis for RLOS or LLOS the Map Point Tool and the Properites buttons show as bright white during the processing time. 

![image](https://user-images.githubusercontent.com/5488313/42338000-67504114-8056-11e8-8dc8-ad39f58e020c.png)

![image](https://user-images.githubusercontent.com/5488313/42337996-62480b3e-8056-11e8-93d7-ae569537737a.png)

### Steps to reproduce

1. Add a elevation layer
2. drop points for observers (select targets if conducting LLOS)
3. Click the OK button

The buttons will flash white

### Expected results
The buttons state should not change during the analysis

**Comment by topowright** [comment]
closing this issue being that it was already logged in the following issue: 

https://github.com/Esri/visibility-addin-dotnet/issues/288

My mistake

**Comment by BobBooth** [comment]
Duplicate of
https://github.com/Esri/visibility-addin-dotnet/issues/288
