### ISSUE TITLE
Bad error message when the add-in cannot create the feature dataset

### ISSUE THREAD

**Issue by dfoll** [Esri/visibility-addin-dotnet#294]
ArcGIS Pro 2.2

#### Current behavior
When the add-in runs and tries to create a feature class that already exists in the geodatabase, the tool fails. That is expected, however the error the user sees is not very useful. When you run the LLOS tool from the add-in, you a CreateFeatureclass_management error, but it does not explain to the user that it is happening because there is already a feature class that exists with the name it is trying to create

#### Expected behavior
We should display a more useful message to the user explaining that a feature class with that name already exists so they understand the tool is not broken and also explains why it works all of the sudden when they try the same thing again.

#### Repro steps
1. Open ArcGIS Pro, start a new project so the default .gdb is empty, open the Visibility add-in, have elevation data in your map.
2. Run the LLOS Visibility tool to generate some results. 
the first set of results is a feature dataset named "LLOS" 
3. Run the LLOS Visibility tool again to generate another set of results
this feature dataset with have a "_1" appended to it, all feature classes in that feature dataset with have "_1" appended to their name
4. Add the [LLOS.lpkx](https://github.com/Esri/visibility-addin-dotnet/tree/dev/source/addins/ProAppVisibilityModule/Data) to the map
note that in the geodatabase this creates a set of features appended with "_2"
5. Run the LLOS tool again to attempt to generate results
the tool understands that it should be appending "_2" to this set of results but doesn't understand those feature classes already exist in the .gdb and you get an error message that is not useful
6. Click OK to dismiss the error message
7. Click Ok to dismiss the warning that computations did not complete (sometimes this is popping up behind the Pro window but I can't repro it well enough to write an issue for it)
8. Run the LLOS tool again to generate results
the tool understands that on this run of the tool it should be appending "_3" and the tool runs successfully again

![image](https://user-images.githubusercontent.com/5322669/43294977-eaa13fea-90f6-11e8-9b6c-0abfdaec20e3.png)

**Comment by dfoll** [comment]
@lfunkhouser @topowright  leaving the pipeline as New Issues. This is a result of the enhancements CT has   done for us, but don't know if we want them to fix this in this delivery or the future.

**Comment by BobBooth** [comment]
Seems like the tool should start a loop, check the GDB to see if the name is already in use, increment the number, recheck, and exit when the dataset name is unique.

**Comment by dfoll** [comment]
we met with @saip he was able to repro, understands the problem and believes he has a way forward

**Comment by topowright** [comment]
We need to make sure we are checking for each individual layer in the geodatabase, the feature set name and the group layer in the Table of Contents.

**Comment by topowright** [comment]
This has been addressed and can be closed. This was delivered with August 2018 release. It was not a known issue because it was introduced during this last update.
