### ISSUE TITLE
Give pre-emptive data frame/surface spatial reference mismatch error message

### ISSUE THREAD

**Issue by dfoll** [Esri/visibility-addin-dotnet#306]
### Background
Visibility add-in displays a message that the LLOS computations did not complete if there is a mismatch with the data frame and surface spatial references.  That is not the problem, but if you want to repro that:
1. Add ElevationUTM_Zone10 to a map
2. Make sure the data frame is set to other than WGS 1984 UTM Zone 10N
3. Try to run LLOS add-in with some points.

### Current behavior
After clicking OK to attempt to run LLOS from the add-in, an error is displayed.
![image](https://user-images.githubusercontent.com/5322669/46581299-157fe180-c9eb-11e8-9b2b-3ec727b08b4d.png)
![image](https://user-images.githubusercontent.com/5322669/46581303-1c0e5900-c9eb-11e8-8393-eb16b1d86d8f.png)

### Expected behavior
User should be warned before attempting to enter input points and clicking OK that the spatial references do not match.'

![image](https://user-images.githubusercontent.com/5322669/46581347-cf774d80-c9eb-11e8-998f-7e78ad7d6a2f.png)
_this is the setup situation_

Before input points can be entered and the OK button is made active, an error indicator is displayed, that the user can hover over for more details
![image](https://user-images.githubusercontent.com/5322669/46581434-9c35be00-c9ed-11e8-9142-410dfe337a0d.png)
_this is a mocked up image of the intended enhancement_

For Pro and ArcMap

**Comment by dfoll** [comment]
@lfunkhouser for prioritization

**Comment by dfoll** [comment]
@saip in the case of both ArcMap and ArcGIS Pro, the warning is happening correctly. Is it possible for the `OK` button to be disabled until the spatial references match?

**Comment by dfoll** [comment]
### Doc QC work 
- [ ] {Visibility October Resources](https://solutionsdev.arcgis.com/defense/help/visibility/resources/october-2019-visibility.htm)
- [ ] \DefenseSolutions\Visibility\October2019\Dev\77\
- [ ] [Military Tools October Resources](https://solutionsdev.arcgis.com/defense/help/military-tools/resources/october-2019-military-tools-for-arcgis.htm)
- [ ] \DefenseSolutions\MilitaryToolsforArcGIS\October2019\Dev\340\

**Comment by lfunkhouser** [comment]
verify doc on PDF Vis build 79 and MT build 345 and dev website

**Comment by dfoll** [comment]
@saip  @CTLocalGovTeam  I thought I heard there would be a delivery for this on 26September. Is my [comment](https://github.com/Esri/visibility-addin-dotnet/issues/306#issuecomment-532719061) something you will be able to review (and deliver if it is doable) early in the day on Monday?

**Comment by dfoll** [comment]
Looks good in ArcGIS Pro 2.4 and ArcMap 10.4.1 ... Vis build 80

![image](https://user-images.githubusercontent.com/5322669/65796563-f8cc4480-e13a-11e9-9882-72c87e08a97f.png)
