### ISSUE TITLE
RLOS output layer labels spelling error

### ISSUE THREAD

**Issue by mfunk** [Esri/visibility-addin-dotnet#311]
Found in Mil Tools 3.3 build 183. Running RLOS  in Pro the output layer contains spelling error, where the Observer points are labeled "In side Extent"...

![image](https://user-images.githubusercontent.com/3093182/51327711-bb99a980-1a26-11e9-8732-51f03078d77c.png)

Where it should be "Inside Extent".

Occurrences: https://github.com/Esri/visibility-addin-dotnet/search?utf8=%E2%9C%93&q=in+side&type=

**Comment by csmoore** [comment]
This spelling fix was included in PR #326

**Comment by dfoll** [comment]
- verified fixed with vis build 64 which was built from [this branch](https://github.com/Esri/visibility-addin-dotnet/tree/csm-314-bad-llos-with-feature-layer) which is [this pr](https://github.com/Esri/visibility-addin-dotnet/pull/326)
