### ISSUE TITLE
Selecting existing feature classes for Observer/Target Points results in bad sight lines (ArcMap Only)

### ISSUE THREAD

**Issue by csmoore** [Esri/visibility-addin-dotnet#314]
On LLOS tab if you select an existing feature class for the inputs for Observer/Target Points - the analysis is incorrect. 

1. The sight lines appear way, way outside of the basemap extent, nowhere near the input points
2. The sight lines are all green
3. This may be a projection issue

Repro steps:

1. Launch ArcMap, create a new blank map
2. Using our standard [test data from military-tools-geoprocessing-toolbox]https://github.com/Esri/military-tools-geoprocessing-toolbox/tree/dev/utils/testdata], add
    a. ElevationUTM_Zone10
    b. LLOS_Targets
    c. LLOS_Observers
3. On the LLOS Tab set
    a. Input Surface: ElevationUTM_Zone10
    b. Observer Points: LLOS_Observers
    c. Target Points: LLOS_Targets
4. Bad results noted above

Screenshot of sightlines appearing outside of basemap / coordinate system and are incorrect (all green)

![image](https://user-images.githubusercontent.com/3090809/51706517-ad322b80-1fec-11e9-804a-5cf837da4858.png)

**Comment by BobBooth** [comment]
Possibly related to the Elevation layer and points not being in same coordinate system?
![image](https://user-images.githubusercontent.com/3801392/51708454-f0db6400-1ff1-11e9-8f90-6487d39ea4e0.png)

**Comment by lfunkhouser** [comment]
@csmoore is it possible to put a limitation on LLOS - restrict user from selecting an existing feature class for inputs for Observers/Targets until we can implement a proper fix?

**Comment by csmoore** [comment]
We could fall back to that as a last resort for ArcMap - we may also be able to add a reproject

**Comment by csmoore** [comment]
This should be addressed in #326 - no need to implement a [workaround](https://github.com/Esri/visibility-addin-dotnet/issues/314#issuecomment-502725611)- it looks like there was just a missing reproject (which oddly was the same issue in https://github.com/Esri/distance-direction-addin-dotnet/issues/667 )

**Comment by dfoll** [comment]
- verified the issue as a problem
- verified fixed (on 10.4.1) with vis build 64 which was built from [this branch](https://github.com/Esri/visibility-addin-dotnet/tree/csm-314-bad-llos-with-feature-layer) which is [this pr](https://github.com/Esri/visibility-addin-dotnet/pull/326)

![image](https://user-images.githubusercontent.com/5322669/59930287-a202f080-9410-11e9-8762-deb1db99c369.png)

**Comment by dfoll** [comment]
Starting on doc now... this one will take a little extra because we do not have any june 2019 information for this one yet....

- [ ] updated what's new page
   - [ ] add to mt section
   - [ ] add a vis section
- [ ] update vis home page
   - [ ] update navigation link for resources to june page
   - [ ] update required software
   - [ ] update what's new table
   - [ ] update contents section
- [ ] add info to mt june release page
- [ ] create vis june release page
- [ ] update vis contents page
- [ ] add vis june release page to resources map
- [ ] update vis config
- [ ] add vis june release page to pdf map

**Comment by dfoll** [comment]
GitHub updates in  [this PR](https://github.com/ArcGIS/arcgis-solutions-website/pull/7895)

**Comment by dfoll** [comment]
G-Doc (CMS) label will be removed after publishing/building tasks are completed

**Comment by dfoll** [comment]
- [What's new](https://solutionsdev.arcgis.com/defense/what-is-new/)  (will require the 1200 pdt build to happen first)
- https://solutionsdev.arcgis.com/defense/help/military-tools/resources/june-2019-military-tools-for-arcgis.htm
- \\...\DefenseSolutions\MilitaryToolsforArcGIS\Dev\309\
- https://solutionsdev.arcgis.com/defense/help/visibility/resources/june-2019-visibility.htm
- \\...\DefenseSolutions\Visibility\Dev\66\

**Comment by lfunkhouser** [comment]
verified on solutionsdev
verified in PDFs from dev builds MT (310) and Vis (66)

**Comment by lfunkhouser** [comment]
@dfoll what's new link points to January 2019 not June for Visibility.

**Comment by dfoll** [comment]
@lfunkhouser  link fixed in [this pr](https://github.com/ArcGIS/arcgis-solutions-website/pull/7914)

**Comment by lfunkhouser** [comment]
What's new link updated. Closing.
