### ISSUE TITLE
Buttons do not support dark theme

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/visibility-addin-dotnet#316]
The following buttons do not follow dark theme:
- Edit Properties
-  Observer Map Point Tool
-  Target Map Point Tool

MT 3.3 January 2019 Release
Tested on Pro 2.2 and 2.3

**Comment by dfoll** [comment]
The following buttons do not follow dark theme:
- [ ] Edit Properties
- [ ] Observer Map Point Tool
- [ ] Target Map Point Tool

**Comment by dfoll** [comment]
@saip the button for `Edit Properties` has an extra light blue border around it. The default look for that button should be the same as what was implemented in this fix for Observer Map Point Tool/Target Map Point Tool. Those buttons are both "plain" with a hover action... `Edit Properties` button should behave the same.

![image](https://user-images.githubusercontent.com/5322669/65162745-b488c800-da07-11e9-8e22-bb6976fc840f.png)
_button does not need border, note there is no border on Observer Map Point Tool/Target Map Point Tool _

![image](https://user-images.githubusercontent.com/5322669/65162975-2eb94c80-da08-11e9-928f-54c9d0c77ca8.png)
_Edit Properties button should get the same hover action as Observer Map Point Tool_

**Comment by dfoll** [comment]
### Doc QC work 
- [ ] {Visibility October Resources](https://solutionsdev.arcgis.com/defense/help/visibility/resources/october-2019-visibility.htm)
- [ ] \DefenseSolutions\Visibility\October2019\Dev\77\
- [ ] [Military Tools October Resources](https://solutionsdev.arcgis.com/defense/help/military-tools/resources/october-2019-military-tools-for-arcgis.htm)
- [ ] \DefenseSolutions\MilitaryToolsforArcGIS\October2019\Dev\340\

**Comment by lfunkhouser** [comment]
verified doc updates on dev site for Vis and MT and PDFs on build 345 MT and Vis 79

**Comment by dfoll** [comment]
@saip  @CTLocalGovTeam  I thought I heard there would be a delivery for this on 26September. Is this something you will be able to deliver early in the day on Monday?

**Comment by dfoll** [comment]
![image](https://user-images.githubusercontent.com/5322669/65796133-ddad0500-e139-11e9-9d60-f7ba38eed3f0.png)
