### ISSUE TITLE
Incorrect results with projected DTED

### ISSUE THREAD

**Issue by mfunk** [Esri/visibility-addin-dotnet#32]
So i'm working with a projected DTED from issue #31. This was in Geographic WGS 1984, but is now in California State Plane Feet. The **LLOS** tool is running, and producing some results, but they are not correct. The lines are ALWAYS visible. The below graphic shows results from several runs on the surface, many of which have a LOT of intervening elevation changes that are much greater than the default 2 Meter observer offset could possibly account for. As you can see in the screenshot, all of the targets are visible from all of the observers.

![image](https://cloud.githubusercontent.com/assets/3093182/13677939/0d32bb40-e6a1-11e5-80a9-6be8f5ebc6bd.png)

If I use the **LLOS** GP Tool I get different results...
![image](https://cloud.githubusercontent.com/assets/3093182/13678259/8dc822d0-e6a2-11e5-97e3-2d38883d498f.png)

Looking at the profile graph of the top most line it looks like the results are legitimate:
![image](https://cloud.githubusercontent.com/assets/3093182/13678290/b798bb42-e6a2-11e5-8cf5-0912cffc382f.png)

I'm thinking this might be projection related. If I use the Geographic n36.dt1 surface with the GP tool the result are NULL points and lines, meaning there is no result produced.

**Comment by mfunk** [comment]
@topowright from demo today, it apparently is.

**Comment by topowright** [comment]
Closing this issue based on the fact that i cannot replicate the issue.
