### ISSUE TITLE
Visibility Certification Testing for ArcMap 10.7.1

### ISSUE THREAD

**Issue by ljuru** [Esri/visibility-addin-dotnet#325]
## Prerequisites

[Visibility (ArcMap)](http://solutions.arcgis.com/defense/help/visibility/)

#### Install Visibility.esriAddIn by clicking on the Add-In

- [x] On the Esri ArcGIS Add-in Installation Utility, check the following:
    * Name, Author, Description
    * Version
    * Digital Signature(s)
- [x] Click "Install Add-In" and the Add-In successfully installs.
- [x] Launch ArcMap, verify the Military Tools Toolbar is automatically added to ArcMap.
- [x] Add the Open Visibility button to the toolbar.
- [x] On the ArcMap Add-in Manager, verify the add-in information for the Military Tools add-in.

#### Visibility Add-in Prerequisites:

To test the Visibility Add-in, you will need the following types of data:

1. Local raster elevation/surface data
2. Local mosaic dataset with elevation data
3. Remote elevation service (See: Note `2`)

Some important caveats/limitations for using this data in the add-in to perform visibility analysis:

1. The elevation data must be in a projected coordinate system
2. The spatial reference of the the map and the elevation data must be the same

Notes:
1. Sample elevation data is available at: https://github.com/Esri/military-tools-geoprocessing-toolbox/tree/dev/testdata/Elevation
2. Currently the elevation service must be a local area of interest (not country or world-wide) - see Issue: https://github.com/Esri/visibility-addin-dotnet/issues/175

### Visibility Add-in Pane

- [x] From the ArcMap Customize Menu, select Customize Mode and locate the visibility button under Commands | Add-in Controls
- [x] Add the visibility button to an existing toolbar, click the button
- [x] Visibility pane will open
- [x] LLOS, RLOS tabs are shown

#### Test with Several Elevation Types

Run the test procedures below on several different elevation data types including:

- [x] Local elevation/surface data
- [ ] Local mosaic dataset with elevation data
- [ ] Remote elevation service

#### Linear Line of Sight(LLOS)

Run linear line of sight tool with each elevation data type. Set multiple:

1. Observer points
2. Target points
3. Offset values
4. Measurement Units

Verify

- [ ] LLOS runs properly
- [ ] LLOS observer and target points symbolize properly
- [ ] LLOS sight lines symbolize properly
- [ ] LLOS takes into account offsets set (ex. by comparing resulting sight lines with/without offsets)
- [ ] Measurement units are correct (compare with Measurement Tool)

#### Run Radial Line of Sight(RLOS)

Run the radial line of sight tool with each elevation data type. Set multiple:

1. Observer points
2. Offset values
3. Minimum and Maximum Ranges
4. Minimum and Maximum Horizontal and Vertical Fields of View
5. "Symbolize Non-Visible Data" set to true/false
6. Measurement Units

- [ ] RLOS runs properly
- [ ] RLOS visible areas symbolize properly
- [ ] RLOS non-visible areas symbolized if checkbox checked
- [ ] RLOS takes into account offsets set
- [ ] RLOS minimum and maximum ranges and fields of view show correctly in output
- [ ] Measurement units are correct (compare with Measurement Tool)

### Issue 114 Check
  https://github.com/Esri/visibility-addin-dotnet/issues/114
- [ ] Enter The following coordinate in the Observer Points box: 116.948W 34.73N
  - Press Enter
- [ ] Enter The following coordinate in the Target Points box: 36.73N 118.948W
  - Press Enter
  - Results should show a line with visible and non visible sections (green and red)

## Final Checks
- [ ] Issue updated with any steps or actions that were taken during the certification
- [ ] Bugs found and logged with appropriate labels (i.e. add the G-documentation label if it affects documentation)
- [ ] Issues addressed/fixed during certification
- [ ] If fixes were made to the solution, open an issue in the solutions-defense repo to update the solution and add for inclusion in the next Release.

**Comment by lfunkhouser** [comment]
Closing. Duplicate issue in solutions-defense test repo
