### ISSUE TITLE
Linear Line of sight produces inaccurate results if data frame coordinate system is changed with Visibility inputs in display

### ISSUE THREAD

**Issue by dfoll** [Esri/visibility-addin-dotnet#327]
## Repro steps:

ArcMap (_steps written using 10.7.1, but this behavior exists back to 10.4.1_) (_steps were tested with both the released version of MT (3.4.0.227) and what was the dev build of MT at the time of writing (3.5.0.311) )_

0. Start with a new ArcMap session
1. Add the topographic basemap [data frame coordinate system will be WGS 1984 Web Mercator (auxiliary sphere]
2. Add and zoom to ElevationUTM_Zone10
3. Add an observer point
4. Add a target point
5. Click OK to run - receive the expected "Please change the spatial reference" message
6. Change the data frame coordinate system to WGS_1984_UTM_Zone_10N
7. Click OK to try to run analysis

_**Results appear far off to the left/west of the map**_

**ADDITIONAL ISSUE/NOTE:** On some versions of ArcMap (10.5.1-10.7) - it is also sometime observed that you are unable to get analysis results after changing the data frame coordinate system. You cannot add points to the map with the visibility add point tool  because they are graphics based, however even if you try to run an analysis using layers from the TOC, the analysis does not work, because the results or the analysis are graphics based.

### Alternate cases that do not cause the problem: 

0. Start with a new ArcMap session
1. Add the topographic basemap [data frame coordinate system will be WGS 1984 Web Mercator (auxiliary sphere]
2. Add and zoom to ElevationUTM_Zone10
3. Add an observer point
4. Add a target point
5. Click OK to run - receive the expected "Please change the spatial reference" message
6. Click Cancel to remove inputs from display
_steps 6, 8, and 9 are a deviation from the original repro steps listed above_
7. Change the data frame coordinate system to WGS_1984_UTM_Zone_10N
8. Add an observer point
9. Add a target point
10. Click OK to try to run analysis

_**analysis runs and appears correct**_

0. Start with a new ArcMap session
1. Add the topographic basemap [data frame coordinate system will be WGS 1984 Web Mercator (auxiliary sphere]
2. Add and zoom to ElevationUTM_Zone10
3. Change the data frame coordinate system to WGS_1984_UTM_Zone_10N
4. Add an observer point
5. Add a target point
10. Click OK to try to run analysis

_**analysis runs and appears correct**_

It seems that out of the three cases, the one failure case is when you change the coordinate system of the data frame with LLOS input points still in the display.

**Comment by lfunkhouser** [comment]
@dfoll Should list as a known issue in doc

**Comment by dfoll** [comment]
@lfunkhouser known issue listed
- https://solutionsdev.arcgis.com/defense/help/visibility/resources/june-2019-visibility.htm
- \\...\DefenseSolutions\Visibility\Dev\68\
- https://solutionsdev.arcgis.com/defense/help/military-tools/resources/june-2019-military-tools-for-arcgis.htm
- \\...\DefenseSolutions\MilitaryToolsforArcGIS\Dev\315\

**Comment by lfunkhouser** [comment]
Verified known issue added solutionsdev and Vis dev build 69 and MT build 316. Moving issue to backlog.

**Comment by csmoore** [comment]
We have several (possibly related) issues related to changing the projection - so would like to take a closer look this sprint now that we are no longer seeing [a similar issue in the SDK sample](https://github.com/Esri/visibility-addin-dotnet/issues/248#issuecomment-503619141) :

https://github.com/Esri/visibility-addin-dotnet/issues/327

https://github.com/Esri/visibility-addin-dotnet/issues/248

https://github.com/Esri/distance-direction-addin-dotnet/issues/527

**Comment by csmoore** [comment]
Addressed in PR: https://github.com/Esri/visibility-addin-dotnet/pull/331

IMPORTANT NOTE: this PR also requires ArcMap **10.7.1** for a fix in that addresses [a related core issue with the Graphics Container](https://github.com/Esri/arcobjects-sdk-community-samples/issues/7). This issue requires the 2 fixes: fix in 10.7.1 and PR #331

**Comment by dfoll** [comment]
|ArcMap Version|Fixed Visibility build 73|
|---|---|
|10.4.1||
|10.5||
|10.5.1||
|10.6|
|10.6.1||
|10.7||
|10.7.1||

**Comment by dfoll** [comment]
|ArcMap Version|Could repro [additional note](https://github.com/esri/visibility-addin-dotnet/issues/327#issue-460001461)|
|---|---|
|10.4.1|no|
|10.5||
|10.5.1||
|10.6|
|10.6.1||
|10.7||
|10.7.1||

**Comment by dfoll** [comment]
With the fixes in [PR 331](https://github.com/Esri/visibility-addin-dotnet/pull/331) this is [fixed](https://github.com/esri/visibility-addin-dotnet/issues/327#issuecomment-518306796) on versions 10.4.1, 10.5, and 10.7.1.  There will be a remaining known issue that will be documented related to [this issue](https://github.com/Esri/arcobjects-sdk-community-samples/issues/7)/BUG-000114828.

**Comment by dfoll** [comment]
### Doc Review:
- [ ] Defense What's new
- [ ] Visibility homepage
- [ ] [Visibility October Resources](https://solutionsdev.arcgis.com/defense/help/visibility/resources/october-2019-visibility.htm)
- [ ] \DefenseSolutions\Visibility\October2019\Dev\75\ 
- [ ] [Military Tools October Resources](https://solutionsdev.arcgis.com/defense/help/military-tools/resources/october-2019-military-tools-for-arcgis.htm)
- [ ] \DefenseSolutions\MilitaryToolsforArcGIS\October2019\Dev\330\

**Comment by csmoore** [comment]
Verified:

Defense What's new -- includes Visibility 
Visibility homepage -- includes October 2019 Release 
Visibility October Resources - includes October 2019 Release Known Issues
Viz Addin PDF - Known Issue present for ArcMap
MT Resources - includes Viz October 2019 Release Known Issues
MT Addin PDF - Viz Known Issue present for ArcMap

Only comment is that we have 2 similar sounding known issues for 10.5.1-10.7 - they may be able to be combined:

![image](https://user-images.githubusercontent.com/3090809/62726953-5fa86980-b9e6-11e9-941c-86cf9d6e7b19.png)
