### ISSUE TITLE
Separate ArcMap and ArcGIS Pro code

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/visibility-addin-dotnet#341]
To prepare for converting the addin to a Pro-only component going forward, we are making some structural changes to the solution:

1. Removing: ArcMapAddinVisibility project/dll
2. Removing: VisibilityLibrary project/dll
3. Refactoring the Pro project to remove dependencies on former VisibilityLibrary 
    a. remove view inheritance
    b. remove no-longer-needed classes (super/abstract classes)
    c. remove mediator/dispatcher (ex: convert to RelayCommands) 
    d. use Pro styling for Dark Mode support
4. As part of this if you notice any hard-coded UI strings that should be converted to Resources (for I18n) please convert these to resources

**Comment by sumitzarkar** [comment]
@lfunkhouser @csmoore @dfoll 

We have commited the code for this tickext, and Implemented following points:
 - Removing: ArcMapAddinVisibilityproject/dll
 - Refactoring the Pro project to remove dependencies on form CoordinateConversionLibrary
    a. remove view inheritance - Completed
    b. remove no-longer-needed classes (super/abstract classes) - Completed
    c. remove mediator/dispatcher (ex: convert to RelayCommands) - In Progress

This is Work In Progress build, and have some build errors.

**Comment by sumitzarkar** [comment]
@lfunkhouser @csmoore @dfoll

We have submitted the Pull request ([link](https://github.com/Esri/visibility-addin-dotnet/pull/342)) for this ticket.

Implemented following points:
 1. ArcMapAddinVisibility project/dll
 2. VisibilityLibrary project/dll
 3. Refactoring the Pro project to remove dependencies on former VisibilityLibrary
     a. remove view inheritance
     b. remove no-longer-needed classes (super/abstract classes)
     c. remove mediator/dispatcher (ex: convert to RelayCommands)
     d. use Pro styling for Dark Mode support 

 4. Localisation
 5. Make necessary changes by removing CoordinateConversionLibrary and replacing with ProCoordinateConversion as done in DistanceAndDirection AddIn.

**Comment by OscarVilla1** [comment]
Findings while testing the ArcGIS Pro Visibility Add-In:
ArcGIS Pro Version 2.5

Test # 4 does not work for either the Linear Line of Sight (LLOS) nor the Radial Line of Sight (RLOS).
       -Using a remote elevation service (WMS): Visibility Add-In failed multiple times.
       -On the LLOS test ---- points for the "Observer" and "Target" get created but no lines displaying 
         the visible/non-visible results are displayed.
       -On the RLOS test ---- tool fails completely
[Instructions:](https://github.com/ArcGIS/solutions-defense-test-catalog/blob/master/Tests/Visibility%20add-in%20test.md)

@lfunkhouser @kgonzago @dfoll @csmoore 

![LLOS_VisibilityAddIn_Test_2MAR2020](https://user-images.githubusercontent.com/60160973/75731055-79bbd900-5ca3-11ea-8b78-2b64a1f2ea4d.JPG)
![VisibilityAddIn_RLOS_RemoteElevServiceTest_Failed_2MAR2020](https://user-images.githubusercontent.com/60160973/75731057-7a546f80-5ca3-11ea-8d75-21502d3afe3b.JPG)

**Comment by csmoore** [comment]
@OscarVilla1 - thanks for testing - I think - based on the results of the last test run: https://github.com/ArcGIS/solutions-defense-test-catalog/issues/248 - that those are existing open issues and not related to this PR

**Comment by lfunkhouser** [comment]
@csmoore will merge PR into a "Pro 2.6 branch"

**Comment by lfunkhouser** [comment]
@OscarVilla1 Please test on Pro 2.6 since this is what we are releasing on.

**Comment by csmoore** [comment]
PR #343 has been tested and merged - closing this issue.
