### ISSUE TITLE
Cancel and Ok buttons do not stay centered when min/max window

### ISSUE THREAD

**Issue by OscarVilla1** [Esri/visibility-addin-dotnet#345]
### Issue
While testing the Visibility Add-In in ArcGIS Pro 2.6 in dark and light theme.
I noticed that the Cancel and OK buttons do not stay centered when window size is changed.

![VisibilityAddIn_Buttons_NotCentered_Together](https://user-images.githubusercontent.com/60160973/75938249-2335d280-5e3c-11ea-95a8-9ee125f39d7d.JPG)

### Expected Behavior
These two buttons should stay centered while altering window size.

### Detailed steps
1. Launch ArcGIS Pro 2.6
2. Open the Visibility Add-In through the Add-In tab
3. Minimize or enlarge window
4. Observe the location of "Cancel" and "OK" buttons.

### Additional Info:
_**ArcGIS Pro Build**_
ArcGIS Pro 2.6.0 alpha3+build 23550

Visibility Add-In Version and Date:
![VisibilityAddIn_2MAR2020](https://user-images.githubusercontent.com/60160973/75935459-157c4f00-5e34-11ea-8880-327d95ec8569.JPG)

**Comment by OscarVilla1** [comment]
@dfoll  please provide feedback

**Comment by dfoll** [comment]
@OscarVilla1 This looks good. The only thing I would add is since 2.6 is not released, include the build number of Pro

**Comment by OscarVilla1** [comment]
Successfully tested on ArcGIS Pro 2.6
Add-In release date: 9 MARCH 2020

Issue has been fixed.
![Visibility_Add_In_Open_Cancel_Button_Centered](https://user-images.githubusercontent.com/60160973/76266049-7b494c00-6223-11ea-8589-ec81f02459c7.JPG)
