### ISSUE TITLE
Browse window does not stay in Dark Theme mode

### ISSUE THREAD

**Issue by OscarVilla1** [Esri/visibility-addin-dotnet#346]
### Issue
While testing the Visibility Add-In in ArcGIS Pro 2.6 in Dark Theme mode.
I noticed that the browse window does not stay consistent with the Dark Theme mode while importing relevant files, such as: .SHP, .txt, .csv, etc.

![DarkTheme_BrowseWindow_ShowsInLightTheme](https://user-images.githubusercontent.com/60160973/75938889-b91e2d00-5e3d-11ea-9e84-3dbaa069c8ce.JPG)

### Expected Behavior
This browse window should stay consistent and match the Dark Theme mode..

### Detailed steps
1. Launch ArcGIS Pro 2.6
2. Open the Visibility Add-In through the Add-In tab
3. Right click below the *Observer Points* or *Target Points* window and select **Import**
4. Observe the background color associated with the *Browse* window

### Additional Info:
_**ArcGIS Pro Build**_
ArcGIS Pro 2.6.0 alpha3+build 23550

#### Visibility Add-In Version and Date:

![VisibilityAddIn_2MAR2020](https://user-images.githubusercontent.com/60160973/75935459-157c4f00-5e34-11ea-8880-327d95ec8569.JPG)

**Comment by OscarVilla1** [comment]
@dfoll  please provide feedback

**Comment by dfoll** [comment]
@OscarVilla1 good issue. I would just add the build number of ArcGIS Pro 2.6, because it is not released yet

**Comment by OscarVilla1** [comment]
Successfully tested on ArcGIS Pro 2.6

Add-In release date: 9 MARCH 2020

Issue has been fixed.
![Visibility_Add_In_Import_DarkTheme](https://user-images.githubusercontent.com/60160973/76265779-c0b94980-6222-11ea-936d-efbff3c5c72c.JPG)
