### ISSUE TITLE
Enhancement Request: RLOS tool should not be enabled to run with unprojected data.

### ISSUE THREAD

**Issue by pshowalter** [Esri/visibility-addin-dotnet#36]
Enhancement Request: disable the OK button and show red X on tool that source input surface is not projected, similar to other GP tools that indicate input is invalid.

As pointed out in a previous issue, https://github.com/ArcGIS/visibility-addin-dotnet/issues/33, a requirement of the RLOS is that source data be projected.  
In some cases, data available to potential users will be GCS_WGS84.

**Comment by topowright** [comment]
This is no longer an issue.
