### ISSUE TITLE
Enhancement: Inform the user if 3D or Spatial Analyst is not available 

### ISSUE THREAD

**Issue by pshowalter** [Esri/visibility-addin-dotnet#40]
Enhancement: Inform the user if 3D or Spatial Analyst is not available.  
When running the RLOS on a system that does not have 3D or Spatial Analyst, The user will receive a message indicating "Results not calculated. Check input parameters, and try again".  It would be better to inform the user that a required 3D or Spatial Analyst extension is not available.

**Comment by topowright** [comment]
Need to verify this in ArcGIS Pro and ArcMap

**Comment by topowright** [comment]
This has been addressed
![image](https://cloud.githubusercontent.com/assets/5488313/25767502/b63a7cd8-31ae-11e7-8615-cf3919ac4a3d.png)
