### ISSUE TITLE
Enhancement Request: Allow manual input of coordinates for Observer and Target

### ISSUE THREAD

**Issue by pshowalter** [Esri/visibility-addin-dotnet#42]
Enhancement Request: Allow manual input, or pasting from Coordinate Conversion tool, of coordinates for Observer and Target in LLOS and RLOS as appropriate.

**Comment by topowright** [comment]
@jmccausland

**Comment by jmccausland** [comment]
@pshowalter please verify

**Comment by pshowalter** [comment]
verified.
