### ISSUE TITLE
Writing Columns and Values from Graphics to Saved Features

### ISSUE THREAD

**Issue by mcalamito** [Esri/visibility-addin-dotnet#47]
Saving graphics as features (shapefile, feature class, and KML) is crucial, but so is saving the attributes that correspond to these features. The user will be inputting information into the Visibility form or drawing on the map interactively. These values must be present in the attribute table when the graphic is saved to a feature or the user will not have values associated with each feature.

For any input field that has a unit, the corresponding Column/Field header name in the attribute will end with "_x" where x = the unit in which defines the input field.

The following columns and values should be included when writing graphics to features:

LLOS: Input_Surf, Observer_Pt, Target_Pt, Obs_Offset_x, Tar_Offset_x - where Input_Surf = input surface file name OR path to file and where x is the unit the user chose from the unit dropdown.

RLOS: Input_Surf, Observer_Pt, Obs_Offset_x, SurfOffset_x, Distance, Horiz_FOV_x, Vert_FOV_x - where Input_Surf = input surface file name OR path to file and where x is the unit the user chose from the unit dropdown.

These are only suggested column names and I welcome any discussion.

**Comment by topowright** [comment]
This issue has been partly resolved. 

In ArcGIS Pro we write features to the default database and we do not need to change anything; however, in ArcMap we need to have LLOS tool write features to the default database. The RLOS tool currently writes to the scratch workspace. It would be good to have this output be the default database for ArcMap as well.

**Comment by topowright** [comment]
This have been implemented in the current release of Military Tools 2.0
