### ISSUE TITLE
Versions for add-in

### ISSUE THREAD

**Issue by topowright** [Esri/visibility-addin-dotnet#51]
Versions for add-in

**Comment by lfunkhouser** [comment]
@topowright Can you modify the title and description of this issue to be more explicit?

**Comment by topowright** [comment]
Each add-in must have a versoin number. If this does not happen and users use a common folder to share the add-ins the system will not know when to pull a new version.

**Comment by topowright** [comment]
![image](https://cloud.githubusercontent.com/assets/5488313/14579329/e698ae6a-0359-11e6-8033-53abf2cde9a1.png)
This is an example of the version number

**Comment by topowright** [comment]
verified
