### ISSUE TITLE
Not seeing correct warning in LLOS with different spatial references

### ISSUE THREAD

**Issue by mfunk** [Esri/visibility-addin-dotnet#61]
So I'm testing for #59 and #58 And I'm expecting to see a warning like:

*Spatial Reference of Data Frame and surface must match.  Please change the Spatial Reference of the Data Frame and try again.*

I set the spatial reference for the Data Frame to Web Mercator:
![image](https://cloud.githubusercontent.com/assets/3093182/14930344/0a19b8f2-0e18-11e6-91f5-5034d7f26441.png)

Then open the Add-In and point to a raster in *Geographic WGS 1984* for **Input Surface**, set observer, target, observer offset:

![image](https://cloud.githubusercontent.com/assets/3093182/14930373/484c6ae8-0e18-11e6-9306-8cf413a12cb1.png)

and click **OK**:

![image](https://cloud.githubusercontent.com/assets/3093182/14930379/50d29d68-0e18-11e6-90e7-e911326e9fc5.png)

If I set the Data Frame to the same coordinate system as the Input Surface layer the tool works nicely.

![image](https://cloud.githubusercontent.com/assets/3093182/14930425/b4a98090-0e18-11e6-910e-6c347775d165.png)

Working on 10.3.1 Final:
![image](https://cloud.githubusercontent.com/assets/3093182/14930388/63926208-0e18-11e6-8089-91555c884757.png)

**Comment by dhagens** [comment]
![llos](https://cloud.githubusercontent.com/assets/13664546/14954579/95a93caa-1041-11e6-8fdc-7745daef35a4.jpg)

It appears that the Application folder was not updated after the last commit that fixed this issue.  @jmccausland, please update the Application folder so Matt can retest these.  Thanks.

**Comment by mfunk** [comment]
Tried again with yesterday (5/2/2016 build 285) and still not getting expected warnings. Tried 4 test cases:

**Case 1:**
* Data Frame: GCS_WGS_1984
* Input Surface: GCS_WGS_1984
* Result: Results look good, output lines are red/green:

![image](https://cloud.githubusercontent.com/assets/3093182/14986374/70add5d6-1100-11e6-9303-a0f0764c5769.png)

**Case 2:**
* Data Frame: GCS_WGS_1984
* Input Surface: NAD_1983_StatePlane_California_IV_FIPS_0404_Feet
* Result: Results totally green. not expected, no error.
![image](https://cloud.githubusercontent.com/assets/3093182/14986425/ba7c9dc8-1100-11e6-9b44-f47bc9bd8a06.png)


**Case 3:**
* Data Frame: NAD_1983_StatePlane_California_IV_FIPS_0404_Feet
* Input Surface: NAD_1983_StatePlane_California_IV_FIPS_0404_Feet
* Result: here results look good again. Red/green lines are what I would expect:
![image](https://cloud.githubusercontent.com/assets/3093182/14986491/03c6d2e6-1101-11e6-9e8a-6299c166b541.png)


**Case 4:**
* Data Frame: NAD_1983_StatePlane_California_IV_FIPS_0404_Feet
* Input Surface: GCS_WGS_1984
* Result: Message: Something went wrong.
![image](https://cloud.githubusercontent.com/assets/3093182/14986553/3e89069c-1101-11e6-98d6-08dba26241f0.png)

**Comment by mfunk** [comment]
Verified and done.
