### ISSUE TITLE
Not seeing correct warning for RLOS using geographic input surface

### ISSUE THREAD

**Issue by mfunk** [Esri/visibility-addin-dotnet#62]
I'm testing the warning messages from PRs #58 and #59 and not getting the expected warning message when using an **Input Surface** in Geographic coordinates.

I'm using a surface dataset in **Geographic WGS 1984**...
![image](https://cloud.githubusercontent.com/assets/3093182/14930656/818e531e-0e1a-11e6-9c55-478250ed40f1.png)

I set a single observer, and click OK... and the status bar swims around..

![image](https://cloud.githubusercontent.com/assets/3093182/14930673/ae71af48-0e1a-11e6-9445-097139425804.png)

But still produces something, even though it shouldn't....

![image](https://cloud.githubusercontent.com/assets/3093182/14930709/e481cfe6-0e1a-11e6-88cd-d2850bdca555.png)

If I change the Data Frame to the same geographic coordinate system it just spins it's status bar:

![image](https://cloud.githubusercontent.com/assets/3093182/14930783/711569ea-0e1b-11e6-8360-430a359d4d01.png)

**Comment by dhagens** [comment]
![llos](https://cloud.githubusercontent.com/assets/13664546/14954666/40fbbc2c-1042-11e6-9a88-c80479120098.jpg)
Same as #61.  @jmccausland, please update the Application folder and comment on here when completed so @mfunk can retest.  Thanks.

**Comment by jmccausland** [comment]
updated, but only because it looks like Jenkins is not working properly

**Comment by mfunk** [comment]
Verified and fixed.
