### ISSUE TITLE
LLOS in Pro not accepting manual input in Observer or Target Points

### ISSUE THREAD

**Issue by pshowalter** [Esri/visibility-addin-dotnet#72]
LLOS in Pro will only allow points to be entered using the Map Point tool.  If you type or paste a coordinate in, it is marked as "Invalid Coordinate".  Using the Mosaic Dataset ".\Resources\Tutorial Data\MilitaryToolsTestData.gdb\ElevationSurface".  
Elevation is Web Mercator
Map is Web Mercator.

![image](https://cloud.githubusercontent.com/assets/6842145/15076792/64e7fe36-1379-11e6-8690-29d79d75903a.png)

**Comment by jmccausland** [comment]
updated, @pshowalter please verify with the late day or tomorrows Jenkins build

**Comment by pshowalter** [comment]
Closing.  Form is accepting Input of typed or pasted coordinates  in LLOS and RLOS.

(I am not getting results with LLOS and the Pro build 5792)
