### ISSUE TITLE
LLOS - not producing results with Pro build 5792.

### ISSUE THREAD

**Issue by pshowalter** [Esri/visibility-addin-dotnet#81]
No results produced with LLOS and the Pro build **5792**.  No error message, runs and no graphics or features result.
Have tried with 2 elevation data sets:
- ElevationSurface Mosaic Data Set  
- ElevationUTM_Zone10 GDB Raster

**Comment by pshowalter** [comment]
@jmccausland @topowright 
With Pro Build 5796 - a first run of LLOS will produce appropriate results.  A second run in the same Map or different Map does not produce the line features.  LLOS overwrites the **vis_los_output** in the Projects GDB, but not the **vis_sight_lines**.  No lines are created for the 2nd run (red/blue points in screen capture).  If we consider this "as designed", (perhaps document a workflow for users to export the lines in order to save them) this issue can be closed?

![image](https://cloud.githubusercontent.com/assets/6842145/15756097/ba2a83c8-28cd-11e6-81f4-0864e74ee580.png)

**Comment by jmccausland** [comment]
All GP tool calls that result in output have the environment "overwriteoutput" set to true

I see this as a Pro core issue

**Comment by jmccausland** [comment]
Also if you have the symbology tab open it can cause your visuals to change.

**Comment by pshowalter** [comment]
@topowright @jmccausland 
Further investigation, it seems that the vis_los_output lines **are created**, have an attribute table, but Pro does not display them.  Additional manipulation of Pro (i.e. export features, then apply a layer file to the new layer of exported  lines, **_zoom out_**) and the original non-displayed lines will display.
In some testing, Save and Quit, reopen the project, lines not displayed, _**zoom**_ out and the lines display, zoom back in, lines do not display. Or after reopening a Saved project, turn on another layer, and the lines start display properly at all zoom levels.

**Comment by jmccausland** [comment]
I'm seeing some GP tool failures due to not being able to acquire a lock.  Calls to GP tools are being made properly.

**Comment by pshowalter** [comment]
It would be great to get this in front of GP developers. I have seen similar in another  template.




<notifications@github.com<mailto:notifications@github.com>> wrote:


I'm seeing some GP tool failures due to not being able to acquire a lock. Calls to GP tools are being made properly.

-

**Comment by topowright** [comment]
We are able to draw and create the features from both tools. However, this still might be connected to a larger issue with the GP functionality.

**Comment by nfeuerstein** [comment]
@topowright @dhagens is this issue resolved with the fix at 1.4?

**Comment by dhagens** [comment]
Yes this should be fixed with the fix made by the Pro team yesterday.

**Comment by topowright** [comment]
I am closing this issue. @dhagens  and I have verified that this is no longer an issue.
