### ISSUE TITLE
Zoom to Graphic Extent After Graphic Created

### ISSUE THREAD

**Issue by mcalamito** [Esri/visibility-addin-dotnet#88]
after creating a graphic, the map should be zoomed to graphic extent by default. If the user is drawing within their current extent, they can see their graphic being created. If they are manually inputting parameters and those parameters fall outside their current extent, they should be automatically taken to the graphics extent.

**Comment by dhagens** [comment]
@elinz Ready for testing

**Comment by topowright** [comment]
I have verfied that this is working in ArcGIS Pro and ArcMap minus the LLOS in ArcMap. This is due to the outputs for LLOS in ArcMap are graphics not features.
