### ISSUE TITLE
Snapping to Features When Interacting with Map in ArcMap

### ISSUE THREAD

**Issue by mcalamito** [Esri/visibility-addin-dotnet#89]
When interacting with map to create center points, end points, etc., snapping to existing features would be a huge workflow asset. It currently works in ArcGIS Pro and is a big enhancement. Having this available in ArcMap is crucial.

**Comment by jmccausland** [comment]
addressed in #90, verify at the next build

**Comment by migueldls** [comment]
@jmccausland @lfunkhouser I verified that the snapping to features in ArcMap works as expected. Verified in ArcMap 10.4.1 and works with point, end, vertex and edge snapping. Going to close this issue.
