### ISSUE TITLE
RLOS output is pink

### ISSUE THREAD

**Issue by mfunk** [Esri/visibility-addin-dotnet#91]
I installed the latest build of the Pro Add-In today, and ran it against the test "ElevationUTM_Zone10" data. One single observer, but the output is PINK:

![image](https://cloud.githubusercontent.com/assets/3093182/16132574/8c8fe632-33c8-11e6-8c0b-a2d1942dbb1d.png)

**Comment by mfunk** [comment]
... and now it is gray/blue and not square...

![image](https://cloud.githubusercontent.com/assets/3093182/16133577/8580721c-33cd-11e6-8d68-a3adec2ea59a.png)

**Comment by topowright** [comment]
I have confirmed that I get the same thing in today's and yesterdays build. Going back to check previous builds

**Comment by topowright** [comment]
Build 457 shows the correct symbology

**Comment by topowright** [comment]
The build number is 4857. I just tested this on 4861 and I am seeing the same issue.

**Comment by topowright** [comment]
This was an issue in ArcGIS Pro 1.3 and was fixed then. This is no longer an issue.
