### ISSUE TITLE
Arcmap and Pro LLOS, and RLOS does not detect point outside of an elevation Mosaic dataset extent that is not rectangular.

### ISSUE THREAD

**Issue by pshowalter** [Esri/visibility-addin-dotnet#94]
@jmccausland @dhagens @topowright @mfunk 
In Arcmap and Pro 1.3, RLOS does not detect user entered point outside of an elevation Mosaic Data Set extent that is not rectangular in an area that would be in the minumum bounding rectangle.
![image](https://cloud.githubusercontent.com/assets/6842145/16739361/b48f0566-4767-11e6-9d69-e05b0713322b.png)

**Comment by topowright** [comment]
This has been fixed in ArcMap: 

![image](https://cloud.githubusercontent.com/assets/5488313/21374165/82d2e05a-c6d9-11e6-97ea-35690aa3f0b0.png)
This needs to be verified in ArcGIS Pro 1.4

**Comment by dhagens** [comment]
Ready to verify in new build.
In Pro, the LLOS and RLOS tools will run if one or more of the Observer / Target points are outside of the surface extent.  The returned results will not be displayed for any points outside of the selected surface extents.  For LLOS and RLOS in ArcMap, all points must be within the extents of the selected surface.  If any points are outside of the selected surface extents, the user will be notified when trying to execute the tool.

**Comment by topowright** [comment]
This will be addressed by documentation.

**Comment by topowright** [comment]
Verified that the warning message happens in ArcMap.
