### ISSUE TITLE
Add-in crashes when multiple sessions are ran

### ISSUE THREAD

**Issue by topowright** [Esri/visibility-addin-dotnet#95]
Thinking about how the user might want to jump back  and forth from LLOS to RLOS a bug has been found that causes ArcGIS Pro to fail. This happens also if you try to run RLOS more than once in ArcGIS Pro 1.2. 

Currently the possible fix is to have the add-in write  a new feature classes each time the tool is being ran.

**Comment by nfeuerstein** [comment]
@topowright is this still an issue or has it been fixed at 1.4?

**Comment by topowright** [comment]
@nfeuerstein This issue has been fixed.
