### ISSUE TITLE
Bad results when running RLOS in ArcGIS Pro 1.2

### ISSUE THREAD

**Issue by topowright** [Esri/visibility-addin-dotnet#97]
When running the RLOS tool sometimes the result returns like the example graphic below: 
![image](https://cloud.githubusercontent.com/assets/5488313/20467019/203d2666-af33-11e6-98f6-7df0f1c7f169.png)

This does not happen every time; however, it does happen and can be reproduced by running the RLOS tool multiple times in a row.

**Comment by nfeuerstein** [comment]
Does this bug still happen in 1.3?

**Comment by topowright** [comment]
@nfeuerstein I am going to close this bug because it is related to ArcGIS Pro 1.2
